### ISSUE TITLE
Fatdog Distro

### ISSUE THREAD

**Issue by nobicycle** [mbusb/multibootusb#100]
This is a wonderfully small and stable distro for low end notebooks.
Multibootusb did not recognise it.
http://distro.ibiblio.org/fatdog/web/

**Comment by alindt** [comment]
fixed in 7b92c202

**Comment by alindt** [comment]
@nobicycle, give the [latest release](https://github.com/mbusb/multibootusb/releases) (8.6.0) a try

**Comment by mbusb** [comment]
Implemented in latest version.

**Comment by nobicycle** [comment]
Tested. Works fine.
Thank you
