### ISSUE TITLE
Feature Request - Grub Boot

### ISSUE THREAD

**Issue by nobicycle** [mbusb/multibootusb#102]
I wondered if you had considered adding a Grub Boot from ISO feature?
It seems to me all the code must already be present in multibootusb. All
that would be required is writing out '/etc/grub.d/40_custom' and
running:
	if test -f /boot/grub/grub.cfg; then
		sudo grub-mkconfig -o /boot/grub/grub.cfg
	else
		echo "$G_ERROR_BULLET Can't find /boot/grub/grub.cfg."
		sudo update-grub
	fi

I find Grub Boot really useful. Iso are sitting on local hard disks.
It is nice to be able to boot one up live from system boot, especially
Ubuntu with its persistence.

**Comment by jphein** [comment]
I would also love to see a generic grub option for booting non-supported ISOs.

**Comment by mbusb** [comment]
Work is under progress. With current state, I can't really push. Just waiting for the module to get some shape.

**Comment by mbusb** [comment]
Please download the source from devel branch and provide feedback. Initial UEFI boot support has been implemented.

**Comment by nobicycle** [comment]
I did so. I saw the first tab  had changed and that the QEMU tab was renamed. But I wan't sure how to use Grub Iso Boot?

**Comment by mbusb** [comment]
ISO boot using grub2 is still not implemented. But you can load from syslinux when booting from USB. This is the first step towards implementation of ISO boot which is there on the pipeline.

**Comment by mbusb** [comment]
Latest version (9.1.0) has the option to boot distro directly to ISO. Therefore, the issue has been addressed. Closing the issue.
