### ISSUE TITLE
Finnix not working out-of-the-box

### ISSUE THREAD

**Issue by f3rn4nd0-c354r** [mbusb/multibootusb#104]
I tried to use multibbotusb with Finnix [https://www.finnix.org/](url) , but got an error because Finnix could not find the media it needs to boot on any device (since it is moved to a subfolder of multibootusb). I was able to mount it manually.

Is there a configuration I can change for this?

Are there guidelines for working out a patch?

Thanks!

**Comment by alindt** [comment]
fixed in 7b92c202

**Comment by alindt** [comment]
@f3rn4nd0-c354r, give the [latest release](https://github.com/mbusb/multibootusb/releases) (8.6.0) a try

**Comment by mbusb** [comment]
Added to latest release.
