### ISSUE TITLE
Hiren's BootCD MiniXP doesn't work

### ISSUE THREAD

**Issue by Cysioland** [mbusb/multibootusb#105]
Other options in Hiren's Boot CD menu I can select no problem, this one gives me

```
INF file txtsetup.sif is corrupt or missing, status 10

Setup cannot continue. Press any key to exit.
```

**Comment by mbusb** [comment]
Yo should report to appropriate forums. Not under the scope of this project.

**Comment by Cysioland** [comment]
But it works when putting in on a standalone USB
