### ISSUE TITLE
"No Bootable Device"

### ISSUE THREAD

**Issue by keith24** [mbusb/multibootusb#106]
I'm getting the error: `No Bootable Device`.  It happens when I boot on my computer or test with QEMU.  

This is what the USB stick looks like after running multibootusb: 

```sh
/media/myusb
└── multibootusb
    ├── bg.png
    ├── chain.c32
    ├── extlinux.cfg
    ├── grub.exe
    ├── ldlinux.sys
    ├── memdisk
    ├── menu.c32
    ├── menu.lst
    ├── syslinux.cfg
    ├── systemrescuecd-x86-4.8.0
    ├── ubuntu-16.04.1-desktop-amd64
    ├── ubuntu-16.04.1-desktop-i386
    ├── ubuntu-16.04.1-server-amd64
    ├── ubuntu-16.04.1-server-i386
    ├── vesamenu.c32
    ├── xubuntu-16.04.1-desktop-amd64
    └── xubuntu-16.04.1-desktop-i386
```

Each iso has become a folder like this: 

```sh
/media/myusb/multibootusb/ubuntu-16.04.1-desktop-amd64
├── boot
├── [BOOT]
├── casper
├── dists
├── EFI
├── install
├── iso_file_list.cfg
├── isolinux
├── md5sum.txt
├── multibootusb.cfg
├── pics
├── pool
├── preseed
└── README.diskdefines
```

Did I miss a step?

**Comment by kennelbound** [comment]
I'm running into the same with the latest.

**Comment by mbusb** [comment]
Can you post the log? It will be located on '/tmp/multbootusb.log'

**Comment by mbusb** [comment]
Did you install the distro on different partition?

**Comment by Majora320** [comment]
I had this issue too, setting the `boot` and `esp` flags on the partition fixed it.

**Comment by mbusb** [comment]
Boot flag is set by multibootusb as well.

**Comment by mbusb** [comment]
Looks like you are using GPT partition table on your USB disk. But multibootusb only supports msdos partition table.

**Comment by keith24** [comment]
That solved it.  

I'd suggest mentioning needing MSDOS in the [guide](http://multibootusb.org/page_guide/), or checking for it when loading mbusb and throwing an error.

**Comment by mbusb** [comment]
GPT support has been added in the devel branch. Need to test under Windows
little before releasing it as new version.
