### ISSUE TITLE
USB not booting

### ISSUE THREAD

**Issue by choman** [mbusb/multibootusb#109]
running 8.5 multibootusb with the following
- ubuntu 16.10 desktop
- ubuntu 16.10 server
- ubuntu mate 16.10 desktop

Installed syslinux

I get the boot menu, but selecting any of the above three distros just returns me to the 
boot menu

UPDATE: I'm running on ubuntu 16.10 and the thumbdrive is ext4, 

UPDATE: same issue with ext3.  Tried making my 128G thumbdrive fat32.  seemed to work.  the grub menu seems to work too.  but shortly after selecting  a distro,  black screen for a very long timem foreverish.

**Comment by alindt** [comment]
> Installed syslinux

You mean you used the **syslinux** tab in the application?

Did you boot the USB drive from **QEMU > Boot USB** or from normal system reboot?

**Comment by mbusb** [comment]
Can you provide the content of the syslinux and extlinux.cfg located under multibootusb directory?

**Comment by mbusb** [comment]
Not enough info. closing the issue.
