### ISSUE TITLE
Can not run.

### ISSUE THREAD

**Issue by eexpress** [mbusb/multibootusb#112]
multibootusb-8.5.0-1.noarch.rpm in fedora 25.

dnf install thost package.
```
(1/4): p7zip-16.02-2.fc25.x86_64.rpm                      510 kB/s | 683 kB     00:01    
(2/4): p7zip-plugins-16.02-2.fc25.x86_64.rpm              472 kB/s | 990 kB     00:02    
(3/4): sip-4.18.1-1.fc25.x86_64.rpm                       119 kB/s | 127 kB     00:01    
(4/4): python-qt5-5.7-4.fc25.x86_64.rpm                   1.0 MB/s | 3.8 MB     00:03    
```

when run.
```
▶ multibootusb
Traceback (most recent call last):
  File "/usr/local/bin/multibootusb", line 18, in <module>
    from scripts.mbusb_cli import *
ImportError: No module named 'scripts'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/multibootusb", line 23, in <module>
    from .scripts.mbusb_cli import *
SystemError: Parent module '' not loaded, cannot perform relative import

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/multibootusb", line 27, in <module>
    import scripts
ImportError: No module named 'scripts'

```

**Comment by smellymoo** [comment]
got the same. fedora 25. installed from rpm.

**Comment by lupoDharkael** [comment]
Same here

**Comment by mbusb** [comment]
Can you run directly from source and report here. When checked last time installing on fedora 25, it worked perfectly fine. I also here many people complaining about 'rpm' package. Patch in respect of creating proper rpm package is welcome.

I also request submitter to check running `python3 multibootusb` instead of `multibootusb`.

**Comment by lupoDharkael** [comment]
I've tested the installation from the `install.py` and everything works perfectly :)

**Comment by mbusb** [comment]
Did any one tested latest release 8.6.0 from RPM package? Please uninstall current installation before installing latest package and provide feedback.

**Comment by lupoDharkael** [comment]
When I try to run multibootusb it the terminal after the rpm installation it shows the following error:
 ```                                                                           
 /usr/bin/env: «python3\r»: No such file or directory  
```

**Comment by mbusb** [comment]
OK. Will fix it in next version and release it today.

**Comment by mbusb** [comment]
Fixed in the latest release. Can someone confirm?

**Comment by lupoDharkael** [comment]
Fedora 25 KDE :
tested in every rpm package it shows the same:
```
Traceback (most recent call last):
  File "/usr/local/bin/multibootusb", line 101, in <module>
    if config.debug is True:
NameError: name 'config' is not defined
```

Fedora 25 XFCE :
```Traceback (most recent call last):
  File "/usr/local/bin/multibootusb", line 18, in <module>
    from scripts.mbusb_cli import *
ImportError: No module named 'scripts'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/multibootusb", line 24, in <module>
    from .scripts.mbusb_cli import *
SystemError: Parent module '' not loaded, cannot perform relative import

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/multibootusb", line 29, in <module>
    import scripts
ImportError: No module named 'scripts'
```

I launched it as `multibootusb` and as `python3 /usr/local/bin/multibootusb` with the same results.

**Comment by mbusb** [comment]
@lupoDharkael I have tested on Opensuse VM. If I use python3 multibootusb, then the error you have reported gone. But it says GUI server cannot be connected. I think the pm packages are installed on python2 site packages. That is my guess. Meanwhile, what happen when you run from source? (please uninstall previously installed packages before trying)

**Comment by mbusb** [comment]
I am pulling my hair out to solve this issue :-((

**Comment by mbusb** [comment]
Ok. Found the issue. The packages are created under debian using standard 'bdist_rpm' command. So, this installs the 'scripts' package in to `/usr/local/lib/python3.4/dist-packages/` directory. Whereas, under rpm based distros, there is no python path `/usr/local/lib/python3.4/dist-packages/` is available. If I add this path on top of the multibootusb script before importing, then everything works fine. I will push the code after testing. I hope this should solve the rpm packaging issue once for all.

**Comment by mbusb** [comment]
Regarding this error:

```python
Traceback (most recent call last):
  File "/usr/local/bin/multibootusb", line 101, in <module>
    if config.debug is True:
NameError: name 'config' is not defined
```
I can safely say that you are getting this error due to one of the following issue:
1.  Installed old version of multibootusb and currently running from sourse
2.  Running multibootusb using python2

**Comment by mbusb** [comment]
Released the new version 8.7.1 with bug fix. I will close this issue if some one confirm that it is working.

**Comment by lupoDharkael** [comment]
Finally! It works in Fedora. You did it :)

**Comment by mbusb** [comment]
Thanks for providing feedback. Closing the issue.

**Comment by infolink-soc** [comment]
`$ python3 multibootusb
Traceback (most recent call last):
  File "multibootusb", line 164, in <module>
    if config.debug is True:
NameError: name 'config' is not defined`

Error also occurs on 8.9.0-1, from Fedora 26. Multibootusb calls for `sys.path.append` under `sys.path.append('/usr/local/lib/python3.4/dist-packages')`.

Was able to solve the issue by changing the import lib to `sys.path.append('/usr/local/lib/python3.5/dist-packages')`.

It then works fine.

**Comment by mbusb** [comment]
The fix was done in the last commit of master.

On 30-Nov-2017 6:45 PM, "infolink-soc" <notifications@github.com> wrote:

$ python3 multibootusb Traceback (most recent call last): File
"multibootusb", line 164, in <module> if config.debug is True: NameError:
name 'config' is not defined

Error also occurs on 8.9.0-1, from Fedora 26. Multibootusb calls for
sys.path.append under sys.path.append('/usr/local/
lib/python3.4/dist-packages').

Was able to solve the issue by changing the import lib to
sys.path.append('/usr/local/lib/python3.5/dist-packages').

It then works fine.

—
You are receiving this because you modified the open/close state.

Reply to this email directly, view it on GitHub
<https://github.com/mbusb/multibootusb/issues/112#issuecomment-348184599>,
or mute the thread
