### ISSUE TITLE
Feature Request - netboot.xyz 

### ISSUE THREAD

**Issue by jphein** [mbusb/multibootusb#116]
https://netboot.xyz/ is a very useful iPXE image that can net-install tons of distributions. It sure would be nice if I could include this on my Multi Boot USB.

Thank you!

What is netboot.xyz?
netboot.xyz is a way to select various operating system installers or utilities from one place within the BIOS without the need of having to go retrieve the media to run the tool. iPXE is used to provide a user friendly menu from within the BIOS that lets you easily choose the operating system you want along with any specific types of versions or bootable flags.

You can remote attach the ISO to servers, set it up as a rescue option in Grub, or even set up your home network to boot to it by default so that it's always available.

**Comment by mbusb** [comment]
Thanks for the suggestion. Added in the development version (non UEFI).

**Comment by jphein** [comment]
Thank you! How do I download the development version?

**Comment by mbusb** [comment]
Hey to push to the repo. I will inform you when I do that.

**Comment by mbusb** [comment]
You can try the devel branch. Closing the issue as the support has been added.
