### ISSUE TITLE
Pool Directory Offline support

### ISSUE THREAD

**Issue by slipttees** [mbusb/multibootusb#120]
I try install ubuntu offline and pool folder doesn't work! somebody else have this problem?

**Comment by mbusb** [comment]
Not understood the problem correctly. Can you explain what is the distro used, what did you try and attach log file.

**Comment by alindt** [comment]
@slipttees, what do you mean by "pool folder"?
Please offer more details on what you're trying to do and what doesn't work as it should.

**Comment by mbusb** [comment]
Closing the issue as it is not clear what user want and what he experienced.
