### ISSUE TITLE
EFI boot

### ISSUE THREAD

**Issue by azrdev** [mbusb/multibootusb#122]
I created a boot USB stick with the current archlinux ISO image, and it boots fine with qemu. However, I'd like to boot it natively from (U)EFI, which works fine with the raw image:
~~~
sudo qemu-system-x86_64 -pflash OVMF.fd -cdrom archlinux-2017.03.01-dual.iso -m 1024
~~~
but using the boot-stick like
~~~
sudo qemu-system-x86_64 -pflash OVMF.fd -hda /dev/sdc -m 1024
~~~
prints the error
~~~
Boot Failed. EFI Floppy
Boot Failed. EFI Floppy 1
Boot Failed. EFI DVD/CDROM
.
~~~

where `OVMF.fd` is the TianoCore firmware `OVMF-X64-r15214.zip` from <https://sourceforge.net/projects/edk2/files/OVMF/>

This is archlinux with 2.8.0-2

**Comment by mbusb** [comment]
Uefi support has been added in the devel branch. Latest commit is yet to be
released. Download the source code from devel branch and try.

**Comment by azrdev** [comment]
@mbusb cool, thanks! however, I just ran into issue #123 :)

**Comment by mbusb** [comment]
Uninstall previous version and install latest one. It works.

**Comment by azrdev** [comment]
This issue still persists with version 8.8.0. Tested with the same firmware image, `archlinux-2017.05.01-x86_64.iso`, I still get the error 
~~~
Boot Failed. EFI Floppy
Boot Failed. EFI Floppy 1
Boot Failed. EFI DVD/CDROM
.
~~~
