### ISSUE TITLE
Crash at 100% when installing KXStudio 14.04.2 

### ISSUE THREAD

**Issue by iSWORD** [mbusb/multibootusb#132]
It's 4 am in the morning and I'm too wasted to look for a duplicate but I just wanted to post this here in case it hasn't been reported yet. I'm running MultiBootUSB 8.5.0 on Linux Mint 18.1 Serena & Python 3.5. I may get a chance to debug it during the weekend but until then, here's some output from the terminal:

```
Installing KXStudio_14.04.2_64bit.iso on /media/root/USB Stick/multibootusb/KXStudio_14.04.2_64bit
ISO extracted successfully. Sync is in progress...
Distro extraction completed...
/media/root/USB Stick/multibootusb/KXStudio_14.04.2_64bit/isolinux/ubuntu.bs
Traceback (most recent call last):########################################### |
  File "/usr/lib/python3/dist-packages/scripts/mbusb_gui.py", line 210, in install_syslinux
    syslinux_distro_dir(config.usb_disk, config.iso_link, config.distro)
  File "/usr/lib/python3/dist-packages/scripts/syslinux.py", line 139, in syslinux_distro_dir
    syslinux_path = os.path.join(multibootusb_host_dir(), "syslinux", "bin", "syslinux") + config.syslinux_version
TypeError: Can't convert 'NoneType' object to str implicitly
```

Looks like a problem with either multibootusb_host_dir() or config.syslinux_version being undefined, but I'm not sure.

By the way, the flash drive already has Windows 8.1 installed.

**Comment by alindt** [comment]
I've tried to reproduce the problem but it didn't show up.
Please run the program from terminal and post the entire run log.
If possible, check the master and/or devel branches and report back.

```
[...]
ISO extracted successfully. Sync is in progress...########################### |
Distro extraction completed...

Found syslinux version 6

/media/alin/USB FAT/multibootusb/KXStudio_14.04.2_64bit/isolinux/ubuntu.bs
[...]
```
![success](https://cloud.githubusercontent.com/assets/1379385/25219732/0601c314-25b8-11e7-82e1-c0dc162ebfdd.png)

**Comment by alindt** [comment]
@iSWORD, give the [latest release](https://github.com/mbusb/multibootusb/releases) (8.6.0) a try

**Comment by mbusb** [comment]
It works.
