### ISSUE TITLE
Feature request: install distros 

### ISSUE THREAD

**Issue by xifi-kif** [mbusb/multibootusb#134]
Hi, the live isos works perfectly, but when I try to install them (tried with many) the installation process stops for various reason (cd-rom not detected, "installation process halted"....).

Is this not supported yet? Will this be implemented?

**Comment by alindt** [comment]
@xifi-kif, give the [latest release](https://github.com/mbusb/multibootusb/releases) (8.6.0) a try

**Comment by mbusb** [comment]
Installing from USB is not the scope of this project. This is an issue with the respective install scripts shipped by distros. Wont and can't be fixed by multibootusb.
