### ISSUE TITLE
Feature request add option to auto accept adding new iso's

### ISSUE THREAD

**Issue by reddwarf4ever** [mbusb/multibootusb#136]
Please add a settings menu and add an option to auto accept new iso's instead of having to click on "yes" every time

Thanks

**Comment by alindt** [comment]
Asking for confirmation is **intended**.

**Comment by mbusb** [comment]
this commit https://github.com/mbusb/multibootusb/commit/336d57f585f7eecade46e51ac21838c23be67434 provides functionality you are requesting for. But you can do this from only CLI.
