### ISSUE TITLE
ISO Panda Cloud not accepted

### ISSUE THREAD

**Issue by reddwarf4ever** [mbusb/multibootusb#138]
ISO Panda Cloud not accepted

**Comment by mbusb** [comment]
Please explain more. Where is the download link of each distro you have posted? You should also mention about the type of OS you use, multibootusb version log of the process you have tried and so on. It is impossible for me to come and see your system to know what went wrong :-)

**Comment by reddwarf4ever** [comment]
Hi
Will update asap with info, is it easy to get this log ?

Also can't get the test USB boot option to work, will try again....but nothing seems to,happen

Thanks.

**Comment by reddwarf4ever** [comment]
I am using windows 10 64 bit pro, the distro was from the developers site, will post link asap, also log file when I work that out.

**Comment by reddwarf4ever** [comment]
This seems to be working now
