### ISSUE TITLE
Gentoo does not find root block device

### ISSUE THREAD

**Issue by SyxbEaEQ2** [mbusb/multibootusb#14]
## Error
When trying to boot a Gentoo live iso (e.g. admincd-amd64-20141006.iso), I get the following error during the boot process:
```
!! Media not found
!! Could not find CD to boot, something else needed?
>> Determining root device...
!! Could not find the root block device in .
!! Please specify another value or:
!! - press Enter for the same
!! - type "shell" for a shell
!! - type "q" to skip...
root block device() :: _
```
## Cause
Gentoo mounts every available partition and serches for a root block. To identify which partition is the right one, it searches for a file called `livecd` in every root directory. The problem is that Multibootusb copies the content of the iso in a subdirectory and not in root, so Gentoo will not find the right partition and won't boot.
## Solution
Place an empty file named `livecd` in the root directory of the multiboot usb stick.

**Comment by mbusb** [comment]
Thanks for the feedback and solution. Will fix this soon.

**Comment by SyxbEaEQ2** [comment]
Fast response^^

**Comment by SyxbEaEQ2** [comment]
Sorry, I didn't wanted to close the issue before the fix...

**Comment by mbusb** [comment]
Bug has been fixed in the new source code. No need to keep files out of multibootusb directory. Closing the issue now.
