### ISSUE TITLE
Question....is it ok to rename Distro ISO's before adding them

### ISSUE THREAD

**Issue by reddwarf4ever** [mbusb/multibootusb#141]
Question....is it ok to rename Distro ISO's before adding them

Wondered if this was affecting the running of distros

**Comment by mbusb** [comment]
Yes you can.

**Comment by reddwarf4ever** [comment]
Hi

Thanks, compiling a list of distros that don't work with URL for ISO but how do I copy the log

Thanks

**Comment by mbusb** [comment]
Upload the file in your repo and post the link here.

**Comment by reddwarf4ever** [comment]
Hello
Thanks, but have never done that before, could you guide me how...

Thanks

**Comment by mbusb** [comment]
If it just a text file, then why don't you copy paste here. Else google is
your best friend.

**Comment by reddwarf4ever** [comment]
Sorry I was referring to the log file, showing distro installs etc.

I have a full list of ISO URL's just need to include the log, as I assume you need that for troubleshooting etc 

Thanks
