### ISSUE TITLE
More feedback required

### ISSUE THREAD

**Issue by MySchizoBuddy** [mbusb/multibootusb#15]
When you click on install syslinux it doesn't give you any responce whether the command worked or failed.
On the QEMU tab it should first detect whether the qemu binary is installed or not. Give an error message if qemu isn't installed.

**Comment by mbusb** [comment]
It already does. Which OS /distro are you using?

**Comment by MySchizoBuddy** [comment]
using linux mint 17.1 rebecca. is there any error log that i can post.

**Comment by mbusb** [comment]
No. I am working on it. I will check again about the issue you have raised.

**Comment by mbusb** [comment]
Fixed the issue. Will be including logging in later releases.
