### ISSUE TITLE
persistence function does not work

### ISSUE THREAD

**Issue by wyk-qyf** [mbusb/multibootusb#159]

**Comment by wyk-qyf** [comment]
windows 10 enterprise
I test linux mint 18.1 cinnamon and ubuntu 16.04 lts desktop, none of them can have persistence. 
I do select the persistence option to 500mb and 1000mb respectively

**Comment by mbusb** [comment]
What do you mean by does not work? Persistence file not created? or no work saved after reboot?

**Comment by wyk-qyf** [comment]
file created, but no work saved after reboot

**Comment by mbusb** [comment]
Can you provide the *.cfg file of isolinux directory (or more exactly isolinux.cfg/ txt.cfg files)

**Comment by wyk-qyf** [comment]
# This file is created by MultiBootUSB.
default vesamenu.c32
prompt 0
menu title MultiBootUSB
MENU BACKGROUND /multibootusb/bg.png
TIMEOUT 300
MENU WIDTH 80
MENU MARGIN 10
MENU PASSWORDMARGIN 3
MENU ROWS 12
MENU TABMSGROW 18
MENU CMDLINEROW 18
MENU ENDROW -1
MENU PASSWORDROW 11
MENU TIMEOUTROW 20
MENU HELPMSGROW 22
MENU HELPMSGENDROW -1
MENU HIDDENROW -2
MENU HSHIFT 0
MENU VSHIFT 0
MENU COLOR border       30;44   #40ffffff #a0000000 std
MENU COLOR title        1;36;44 #9033ccff #a0000000 std
MENU COLOR sel          7;37;40 #e0ffffff #20ffffff all
MENU COLOR unsel        37;44   #50ffffff #a0000000 std
MENU COLOR help         37;40   #c0ffffff #a0000000 std
MENU COLOR timeout_msg  37;40   #80ffffff #00000000 std
MENU COLOR timeout      1;37;40 #c0ffffff #00000000 std
MENU COLOR msg07        37;40   #90ffffff #a0000000 std
MENU COLOR tabmsg       31;40   #30ffffff #00000000 std

# Boot from HDD
LABEL Boot from Hard Drive
MENU LABEL Boot from  Hard Disk
KERNEL chain.c32
APPEND hd1
MENU DEFAULT

# Boot GRUB2
LABEL GRUB2
MENU LABEL Load GRUB2 BootManager
Linux /multibootusb/grub/lnxboot.img
INITRD /multibootusb/grub/core.img
TEXT HELP
    Switch to GRUB2 bootloader for more options. Some distros
    may or may not run on GRUB2, but worth a try. Menu entries
    under GRUB2 are either converted from syslinux config 
    or supported through native grub.cfg/loopback.cfg.
ENDTEXT

# Boot PLoP BootManager
LABEL GRUB2
MENU LABEL PLoP BootManager
KERNEL /multibootusb/plpbt

#start linuxmint-18.1-cinnamon-64bit
LABEL linuxmint-18.1-cinnamon-64bit
MENU LABEL linuxmint-18.1-cinnamon-64bit
BOOT /multibootusb/linuxmint-18.1-cinnamon-64bit/isolinux/ubuntu.bs
#end linuxmint-18.1-cinnamon-64bit
#start cn_windows_10_multiple_editions_version_1607_updated_jul_2016_x64_dvd_9056935
LABEL cn_windows_10_multiple_editions_version_1607_updated_jul_2016_x64_dvd_9056935
MENU LABEL cn_windows_10_multiple_editions_version_1607_updated_jul_2016_x64_dvd_9056935
KERNEL chain.c32 hd0 1 ntldr=/bootmgr
#end cn_windows_10_multiple_editions_version_1607_updated_jul_2016_x64_dvd_9056935
#start ubuntu-16.04-desktop-amd64
LABEL ubuntu-16.04-desktop-amd64
MENU LABEL ubuntu-16.04-desktop-amd64
BOOT /multibootusb/ubuntu-16.04-desktop-amd64/isolinux/ubuntu.bs
#end ubuntu-16.04-desktop-amd64

**Comment by mbusb** [comment]
The isolinux directory is under linuxmint directory.

**Comment by mbusb** [comment]
Just tested the persistence f feature on Linux mint 18. It works perfectly
fine.
