### ISSUE TITLE
After trying to install the deb package, it is unable to import "gen" (gen is not defined)

### ISSUE THREAD

**Issue by allyunion** [mbusb/multibootusb#160]
I believe the issue here:
https://github.com/mbusb/multibootusb/blob/master/multibootusb#L21-L33

Not sure where the deb file is installing the multibootusb library, but shouldn't you call this something like "multibootusblib" instead of scripts?

I really feel like if it was more explicit about the module name, might help to clean up some issues.

`# multibootusb`
`Traceback (most recent call last):`
`  File "/usr/bin/multibootusb", line 84, in <module>`
`    running_from()`
`  File "/usr/bin/multibootusb", line 46, in running_from`
`    gen.log('Running multibootusb version ' + gen.mbusb_version() + ' from installed system...')`
`NameError: name 'gen' is not defined`
`# multibootusb --help`
`Traceback (most recent call last):`
`  File "/usr/bin/multibootusb", line 84, in <module>`
`    running_from()`
`  File "/usr/bin/multibootusb", line 46, in running_from`
`    gen.log('Running multibootusb version ' + gen.mbusb_version() + ' from installed system...')`
`NameError: name 'gen' is not defined`

**Comment by mbusb** [comment]
Gen package is to be available in `/usr/lib/python3/dist-packages/scripts/` directory. Can you check if it is available. Is this path already available in your python path?

**Comment by mbusb** [comment]
I think you are running from source but also installed older version of multibootusb. Resources of multibootusb are set to access from installed path first and source next. Try removing the previous install of multibootusb and run again from source.
