### ISSUE TITLE
can multibootusb support exfat to bootable？

### ISSUE THREAD

**Issue by wyk-qyf** [mbusb/multibootusb#161]
I used exfat format usb disk to make bootable disk, but can not boot from real pc, please help me. I want 4GB larger file transfer between mac and linux and windows

**Comment by mbusb** [comment]
Yet to test.

**Comment by mbusb** [comment]
It appears that syslinux does not support exFAT file system [Look here](http://www.syslinux.org/wiki/index.php?title=Filesystem).

Moreover, the ISO you use also should support the ability to boot from this filesystem which I doubt will do so.
