### ISSUE TITLE
can multibootusb boot windows 10 installation iso? or only works for linux distribution?

### ISSUE THREAD

**Issue by wyk-qyf** [mbusb/multibootusb#162]

**Comment by mbusb** [comment]
What did you try and what is not working? It should support and if not then it is a bug.

**Comment by wyk-qyf** [comment]
l have tried windows 10 ISO on fat USB ,it can not boot . So I have this question.
By the way Can multibootusb support ntfs usb for both windows and Linux iso?

在 2017年5月8日，上午12:15，multibootusb <notifications@github.com<mailto:notifications@github.com>> 写道：


What did you try and what is not working? It should support and if not then it is a bug.

**Comment by mbusb** [comment]
Read this [http://multibootusb.org/page_faq/#can-you-help-me-in-adding-my-favourite-disto-in-to-multibootusb](http://multibootusb.org/page_faq/#can-you-help-me-in-adding-my-favourite-disto-in-to-multibootusb)
