### ISSUE TITLE
Alpine Linux support

### ISSUE THREAD

**Issue by orx57** [mbusb/multibootusb#163]
Hello.

I'm not able to install Alpine Linux iso.

I have test with the following iso:

- https://nl.alpinelinux.org/alpine/v3.5/releases/x86_64/alpine-standard-3.5.2-x86_64.iso
- https://nl.alpinelinux.org/alpine/v3.5/releases/x86_64/alpine-extended-3.5.2-x86_64.iso

Here the log of the test with alpine-extended iso:

- [multibootusb.log.txt](https://github.com/mbusb/multibootusb/files/981720/multibootusb.log.txt)

Thanks!

**Comment by mbusb** [comment]
Will check it out...

**Comment by mbusb** [comment]
Added in the devel branch. Check it out. Will release the new version soon.

**Comment by orx57** [comment]
Works well for me, Thanks!
