### ISSUE TITLE
Hardcoded icon path in launcher for GNU/Linux systems

### ISSUE THREAD

**Issue by palob** [mbusb/multibootusb#17]
Hi,

currently the icon path specified in the created launcher file is set to: 
*Icon=multibootusb.png*

(see https://github.com/mbusb/multibootusb/blob/64f42fecd1c0f7361d5052830daec58bec72690f/data/multibootusb.desktop)

This prevents icon theming without editing the launcher file.

I'd like to ask you to change the icon location as well as the icon path line in the launcher according to the freedesktop.org standards.

Please find more info here:
http://standards.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html
https://github.com/Foggalong/hardcode-fixer/wiki/What,-Why-&-How

---------------------------------
According to the above resources standard icon locations are:

*/usr/share/icons/hicolor/[size]/apps/[icon name]*
*~/.local/share/icons/hicolor/[size]/apps/[icon name]*
*/usr/share/pixmaps/[icon name]*

Your icon *multibootusb.png* is already stored in a standard location (/usr/share/pixmaps).

But the standard icon line in the .desktop launcher is:
*Icon=[icon name]*      (neither full path, nor the file extension are needed)

for instance
**Icon=multibootusb**
(for an icon *multibootusb.svg* or *multibootusb.png* stored in standard location)

Could you please adjust the icon path in the .desktop file accordingly?

**Comment by mbusb** [comment]
Thank you for the feedback. I will fix it soon.

**Comment by mbusb** [comment]
Fixed in the latest source file.
