### ISSUE TITLE
Multibootusb v8.8.0-1 NameError: name 'config' is not defined

### ISSUE THREAD

**Issue by ta2oo** [mbusb/multibootusb#173]
I'm in the directory that the ISO file is located and I'm attempting to load the GParted ISO file onto a USB drive /dev/sdf1 mounted to /media/external. I've used the following commands from the CLI

- sudo multibootusb -c -i /svr/samba/sdd/GParted-ISO/gparted-live-0.27.0-1-amd64.iso -t /dev/sdf1
- sudo multibootusb -c -i gparted-live-0.27.0-1-amd64.iso -t /dev/sdf1
- sudo multibootusb -c -i gparted-live-0.27.0-1-amd64.iso -t /media/external

### Steps to reproduce

Have the GParted ISO available and run the commands above, I've attached a JPEG of the error received.

### System configuration
I'm running Ubuntu 14.04.4 LTS
USB Drive
- Partition table: msdos
- File system: W95 FAT32 (LBA)
- Multiboot version: 8.8.0-1

There is no log file available at /tmp or /var/log

![multibootusb - nameerror](https://cloud.githubusercontent.com/assets/29142269/26720585/c270b994-4780-11e7-89eb-5eaf1e621210.JPG)

**Comment by mbusb** [comment]
What happen when you try `sudo python3 multibootusb -c -i /svr/samba/sdd/GParted-ISO/gparted-live-0.27.0-1-amd64.iso -t /dev/sdf1`?

Are you able to launch GUI?

**Comment by ta2oo** [comment]
Hi.

I get the error message 
> python3: can't open file 'multibootusb': [Errno 2] No such file or directory

I have installed ubuntu-16.04.2-desktop as a VM, installed multibootusb and have sucessfully loaded various ISO's.

Nifty application :-), thank you.
