### ISSUE TITLE
Ubuntu Minimal CD support

### ISSUE THREAD

**Issue by Eskuero** [mbusb/multibootusb#174]
Trying to install the .iso of the minimal Ubuntu disc results into MultiBootUSB telling me that is not supported at the moment. It says Type: None, unlike the standard Ubuntu Desktop .iso which gets detected properly as Type: ubuntu.
Thanks for your work!

**Comment by mbusb** [comment]
Already added in the devel branch. Will release the new version soon.

**Comment by mbusb** [comment]
Latest version should fix this issue. Closing the issue.
