### ISSUE TITLE
Bad quality deb package

### ISSUE THREAD

**Issue by CsatiZoltan** [mbusb/multibootusb#175]
I downloaded the latest (python3-multibootusb_8.8.0-1_all.deb) package and when I want to install it, the following is printed:

`The installation of a package which violates the quality standards isn't allowed. This could cause serious problems on your computer. Please contact the person or organisation who provided this package file and include the details beneath.`

In more details, see the attached file.
[details.txt](https://github.com/mbusb/multibootusb/files/1067366/details.txt)

I use Ubuntu 16.04.
Is it safe to click on `Ignore and install`?

**Comment by tqdv** [comment]
Yes, probably

**Comment by mbusb** [comment]
It is absolutely safe to install the package. The error generated by
lintian is due to shipping of some boot loader  binary packages which are
necessary for successful operation of the application.

Still if you feel that it is not safe, you can download the source code and
run directly from there.

**Comment by mbusb** [comment]
Closing the issue.
