### ISSUE TITLE
multibootusb-pkexec license

### ISSUE THREAD

**Issue by eersoy93** [mbusb/multibootusb#176]
I'm developing [Gonullu GUI](https://github.com/eersoy93/gonullu-gui). I would like take your [multibootusb-pkexec](https://github.com/mbusb/multibootusb/blob/master/multibootusb-pkexec) Bash script code for my project, but you didn't licensed it as GPLv2+ compatible (For example, [multibootusb](https://github.com/mbusb/multibootusb/blob/master/multibootusb) script has been licensed as GPLv2+ compatible). In my opinion, this valuable code should be licensed as GPLv2+ compatible.

**Comment by mbusb** [comment]
Please use it for your project as deemed fit. You can use the licence as the same of multibootusb.

**Comment by eersoy93** [comment]
Thank you.
