### ISSUE TITLE
grub2 unknown filesystem

### ISSUE THREAD

**Issue by pantherra** [mbusb/multibootusb#184]
Hello! I created multiboot usb-hdd with few distros. All working fine except grub2. When entered into grub2, there is an error:
unknown filesystem.
Entering rescue mode
grub rescue> ls
(hd0) (hd0,msdos5) (hd0,msdos2) (hd0,msdos1) 
There are my syslinux.cfg and partition table screenshot.
[syslinux.cfg.txt](https://github.com/mbusb/multibootusb/files/1147460/syslinux.cfg.txt)
![2017-07-14 11-46-31](https://user-images.githubusercontent.com/30169297/28199837-842a0818-688a-11e7-9805-c5201988e1bd.png)
Help me please..

**Comment by Arinerron** [comment]
Getting same error

**Comment by mbusb** [comment]
Issue fixed in latest devel branch. Try and report back.

**Comment by mbusb** [comment]
The latest version 9.2.0 should work well. Please open a new issue if you have one.
