### ISSUE TITLE
UEFI Boot Fails grub prompt

### ISSUE THREAD

**Issue by randyrandersn** [mbusb/multibootusb#186]
Followed website instructions to create multi boot usb stick.

Used gparted to create single partition formatted to fat32, is this right?

Within Manjaro Linux installed mbsub from AUR and added three ISOs (Clonezilla, Tails, Manjaro KDE).  All installed without errors.

Then attempt to boot this USB stick on multiple UEFI booting laptops and it fails directly to the grub prompt.

USB stick root directory
```
$ ls -al
total 24
drwxr-xr-x  4 user user 8192 Jan  1  1970 .
drwxr-x---+ 3 root  root    60 Jul 16 18:32 ..
drwxr-xr-x  3 user user 8192 May 19 12:12 EFI
-rw-r--r--  1 user user    0 Jul 15 18:04 .miso
drwxr-xr-x  6 user user 8192 Jul 15 17:58 multibootusb
```
EFI/BOOT directory
```
$ ls -al
total 2600
drwxr-xr-x 2 user user    8192 Jun  1 20:09 .
drwxr-xr-x 3 user user    8192 May 19 12:12 ..
-rw-r--r-- 1 user user 2630144 May 10 18:52 bootx64.efi
-rw-r--r-- 1 user user      37 May 10 18:52 multibootusb_grub2.txt
```
multibootusb directory
```
$ ls -al
total 624
drwxr-xr-x 6 user user   8192 Jul 15 17:58 .
drwxr-xr-x 4 user user   8192 Jan  1  1970 ..
-rw-r--r-- 1 user user   2052 May 10 18:52 bg.png
-rw-r--r-- 1 user user  20576 May 10 18:52 chain.c32
drwxr-xr-x 9 user user   8192 Jul 15 17:53 clonezilla-live-2.5.2-17-amd64
-rw-r--r-- 1 user user      0 May 10 18:52 extlinux.cfg
drwxr-xr-x 3 user user   8192 Jun  1 20:09 grub
-rwxr-xr-x 1 user user 236977 May 10 18:52 grub.exe
-r--r--r-- 1 user user  37888 Jul 16 04:03 ldlinux.sys
drwxr-xr-x 6 user user   8192 Jul 15 18:03 manjaro-kde-17.0.2-stable-x86_64
-rw-r--r-- 1 user user  25244 May 10 18:52 memdisk
-rw-r--r-- 1 user user  60928 May 10 18:52 menu.c32
-rw-r--r-- 1 user user      2 May 10 18:52 menu.lst
-rw-r--r-- 1 user user   2028 Jul 15 18:04 syslinux.cfg
drwxr-xr-x 8 user user   8192 Jul 15 17:57 tails-amd64-3.0.1
-rw-r--r-- 1 user user 162860 May 10 18:52 vesamenu.c32
```

I am obviously doing something wrong here... any pointers?

**Comment by kaischmerer** [comment]
same here - had to disable UEFI boot. With Legacy Boot the stick is booting (FAT32, MBR).

**Comment by berturion** [comment]
The same for me. Only tried to install boot-repair-disk and I end with a `grub>` prompt on usb boot.

**Comment by payomagic** [comment]
Did you disable Secure Boot first before booting uEFI?

**Comment by berturion** [comment]
@payomagic Yes. The laptop I use can boot any usb live distro (like antergos or linuxmint for example).

**Comment by payomagic** [comment]
@berturion 
ok, Is the EFI file on the USB stick; in correct directory .. ?    Is the EFI file signed? 
If you get into BIOS, there should be possibility to boot from EFI file / check EFI partition or similar 
... you will need to approve EFI file most probably even if signed ... 
Try and let me know, thx . 
Note: 
I was fighting with few specific BIOSes having same problem
 - on AMI helped to update bios to latest ver.  
- on Insyde however i had to sign the EFI file and then approve it

**Comment by openprivacy** [comment]
If I install kali on the USB the suggested way (where it ends up in partition 1) it boots fine:
- `dd if=kali-linux-2017.1-amd64.iso of=/dev/sdb bs=512k`

But if I use `multibootusb` to install in partition 3 (`/dev/sdb3`) then I have to change my BIOS?

**Comment by eaglerainbow** [comment]
@randyrandersn  and @kaischmerer and @berturion : I think I figured out in #242 that this may be related to the USB port to be running on USB 3.0. Could you confirm that your cases fall into the same category?

**Comment by mbusb** [comment]
The latest releases since 9.1.0 has better GRUB2 compatability. Please update your multibootusb to latest version. Open a new issue if have similar problem.
