### ISSUE TITLE
Adding Parabola GNU/Linux-Libre

### ISSUE THREAD

**Issue by lungpu** [mbusb/multibootusb#189]
Hi, your software is great, I've been using it for a big variety of distros and works mostly flawless.
I'd like to suggest the addition of a distro named Parabola. It is based on Arch Linux (actually, it is arch with the not free software removed and linux-libre kernel instead of the classical linux one).
I guess it is very similar to Arch in regards of structure and so.

The download link is here, for a direct link:
https://repo.parabola.nu/iso/2017.05.28/parabola-2017.05.28-dual.iso?noredirect

or here using magnet:
magnet:?xt=urn:btih:27c7a3d8ca74b4a3a694b7c3e6c5a46e54b93ac7&dn=parabola-2017.05.28-dual.iso&tr=udp%3A%2F%2Ftracker.openbittorrent.com%3A80&tr=udp%3A%2F%2Fopen.demonii.com%3A1337&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969

The iso file is around 674M.

This is the download page where I took those links from:
https://wiki.parabola.nu/Get_Parabola

There are two versions of the iso to download, a main one and another one with full Mate desktop. I will be happy having just the main one available but it won't hurt to have them both if you have the time.

The Multiusb version I am using is 8.8.0 on GNU/Linux Mint v.18.2.

Any other info I can provide?
If I can help in any way with this or other issue just let me know.

Thanks!

**Comment by mbusb** [comment]
The support has been added in version 9.2.0.
