### ISSUE TITLE
syslinux install failure

### ISSUE THREAD

**Issue by mbouaziz** [mbusb/multibootusb#19]
After installing a distro, installing syslinux keep stuck on 0%. In the console, the error message is:

```
Updating main syslinux config file...
Traceback (most recent call last):
  File "/usr/local/bin/multibootusb", line 298, in install_syslinux
    self.update_cfg_files.distro_cfg_files()
  File "/usr/local/lib/python2.7/dist-packages/scripts/update_cfg.py", line 171, in distro_cfg_files
    self.main_cfg_file()
  File "/usr/local/lib/python2.7/dist-packages/scripts/update_cfg.py", line 234, in main_cfg_file
    distro_sys_install_bs = distro_syslinux_install_dir + self.iso.isolinux_bin_dir() + '/' + config.distro + '.bs'
TypeError: cannot concatenate 'str' and 'bool' objects
```

I installed multibootusb from github today on Ubuntu

**Comment by mbouaziz** [comment]
FYI, the iso I tried to install is super_grub2_disk_hybrid_2.00s1-beta5.iso

**Comment by mbusb** [comment]
I am aware of this. Super grub2 disk and rescautux are not supported. This distro is based on Debian but does not use syslinux for booting. 

I will solve this issue once I get time.

**Comment by mbusb** [comment]
As of now fixed by omitting the distro (non supported distro). It will remain in wish list.

**Comment by mbusb** [comment]
Closing the issue as the support has been added in the latest version 8.1.0.
