### ISSUE TITLE
[Ubuntu] boot-options missing

### ISSUE THREAD

**Issue by markgraf** [mbusb/multibootusb#195]
Hi there!

I recently put half a dozen distros on USB-Key and noticed that the ubuntu-images were missing boot options, which the same images showed when they were alone on USB-Key ( the latter written with dd).

So on a single-image-USB-key with *buntu i can press "F4" and choose to do an "OEM install".
On a multi-boot-USB-Key, this is not possible.

Working from Manjaro, multibootusb installed from AUR.

Am I doing something wrong?
Or does the menu only support one level of submenus?

Is there a workaround?

Thanks in advance!

**Comment by mbusb** [comment]
All boot options of ach distro install are generated dynamically by multibootusb. Therfore, it is not possible to check each and every option individually. I cant really help in this case.
