### ISSUE TITLE
No RHEL support?

### ISSUE THREAD

**Issue by Alkaris** [mbusb/multibootusb#199]
Referencing Issue: #192

No support for RHEL based Linux ISO image files? How and when can we expect support for this to happen? I wouldn't of thought it been that difficult to support RedHat systems like Fedora and RedHat Enterprise Linux.

**Comment by mbusb** [comment]
RHEL support has been added since version 9.1.0. But ensure that you just copy the ISO files to '/multibootusb/iso' directory and while booting from USB, select 'Scan and boot ISO' option under GRUB2.
