### ISSUE TITLE
win10 not supported

### ISSUE THREAD

**Issue by mbouaziz** [mbusb/multibootusb#20]
That would be great

**Comment by mbusb** [comment]
Ya, that would be great; -))

**Comment by rubdos** [comment]
I got it to work (it started booting) by extracting the iso and manually editing the syslinux.cfg file:

```
#start Win10_1511_Dutch_x64
LABEL Win10_1511_Dutch_x64
MENU LABEL Win10_1511_Dutch_x64
KERNEL chain.c32 hd0 1 ntldr=/bootmgr
#end Win10_1511_Dutch_x64
```

Problem is that you have to extract it to the root of the USB, otherwise Microsoft complains. It gives me a kinda messed up root directory --"

**Comment by op3** [comment]
I tried that, but then only Windows would boot immediately. So instead, I just extracted the Windows iso to a different partition (the first one (NTFS) in my case, multibootusb is on the second partition (ext4 with boot flag)), copied the bootmgr file to `/multibootusb/Win10_1511_German_x64/bootmgr` and manually edited the `syslinux.cfg` file:
```
#start Win10_1511_German_x64
LABEL Win10_1511_German_x64
MENU LABEL Win10_1511_German_x64
KERNEL chain.c32 hd0 <PARTITION> ntldr=/multibootusb/Win10_1511_German_x64/bootmgr
#end Win10_1511_German_x64
```
In my case, `<PARTITION>` has to be `1`. You could probably have multiple Windows installations on different partitions, but I don’t think this would be easy to automate for multibootusb.

**Comment by mbusb** [comment]
The issue I can see is that the Windows ISO you have is not a proper ISO file. It is  ISO-13346 "UDF" file system which is not supported by the software at the moment. Will try to include the same in future release.

**Comment by mbusb** [comment]
Window ISOs are supported now. Try the version 8.1.0. It should work.
