### ISSUE TITLE
OSFclone is not supported

### ISSUE THREAD

**Issue by spacepatcher** [mbusb/multibootusb#201]
Hello!

I'm trying to create a multi-boot USB drive using the MultiBootUSB (v8.8.0) utility. I would like to add OSFclone live CD (https://www.osforensics.com/tools/create-disk-images.html, a popular distro for digital forensics operations) to the set of live CDs, but I can not do this because of the "No support" error.

Could you add support for OSFclone iso?

I have:
1. Host Operating system: **Windows 10**
2. The ISO I am trying to create: **OSFclone (https://www.osforensics.com/tools/create-disk-images.html)**
3. USB disk information: **USB Flash, NTFS, 128Gb**
4. MultiBootUSB version: **v8.8.0**
5. OSFclone based on **Linux box 4.2.9-tinycore**

Thanks!

**Comment by mbusb** [comment]
Added the distro in the latest devel branch.
