### ISSUE TITLE
GUI Cannot Start on Fedora 26

### ISSUE THREAD

**Issue by smartdogreksio** [mbusb/multibootusb#202]
Installed multibootusb-8.8.0-1.noarch.rpm in fedora 26 and installed the required files (p7zip and python3-qt5)

Running with python3
```
[root@localhost bin]# python3 multibootusb
Running multibootusb version 8.8.0 from installed system...
Starting multibootusb GUI...
No protocol specified
QXcbConnection: Could not connect to display :0
Aborted (core dumped)
```

Without "python3" but in the multibootusb directory:
```
[root@localhost bin]# ./multibootusb
Running multibootusb version 8.8.0 from installed system...
Starting multibootusb GUI...
No protocol specified
QXcbConnection: Could not connect to display :0
Aborted (core dumped)
```

With sudo instead of being root
```
[reksio@localhost Downloads]$ sudo /usr/local/bin/multibootusb
Running multibootusb version 8.8.0 from installed system...
Starting multibootusb GUI...
No protocol specified
QXcbConnection: Could not connect to display :0
Aborted
```

Earlier I was getting an error about colors not being imported but the error doesn't show up anymore...

When I run:
`[root@localhost bin]# export DISPLAY=:0; python3 multibootusb --update`
or
`[reksio@localhost Downloads]$ sudo /usr/local/bin/multibootusb --platform-offscreen`
I'm getting the multibootusb help page print out, so multibootusb is technically operational and I'll still be able to use it, but the GUI does not work. 

Not sure why or what exactly is the problem. Went through some forums just now, install packages like "qt5-devel" or "Package-Kit-Qt5" that were supposed to help but the problem still persists. If there's nothing that can be done on your side, then I guess it's fine. I'll just use the command line

**Comment by mbusb** [comment]
Seems like issue with kde. Similar issue was reported when users used manjaro.

**Comment by peddrinn** [comment]
The Solution of the problem:

Give multibootusb the rights to access the X-Server with:

xhost +local:multibootusb
