### ISSUE TITLE
Antergos does not boot

### ISSUE THREAD

**Issue by sirex** [mbusb/multibootusb#204]
Here is what I get:

![virtualbox_antergos_28_09_2017_21_08_19](https://user-images.githubusercontent.com/297583/30982841-5220bb30-a491-11e7-80bb-a739a17a77ae.png)

![virtualbox_antergos_28_09_2017_21_08_33](https://user-images.githubusercontent.com/297583/30982848-58280bc8-a491-11e7-8a25-89569b78e4f2.png)

![virtualbox_antergos_28_09_2017_21_08_55](https://user-images.githubusercontent.com/297583/30982852-5bf79156-a491-11e7-879d-43c2d016c42b.png)

I was using this iso image:

http://mirrors.antergos.com/iso/release/antergos-17.9-x86_64.iso.torrent

**Comment by denisfalqueto** [comment]
There's a problem in Multiboot way of writing the syslinux.cfg. First, there are more than one syslinux.cfg. Their location is:

- /multiboot/${antergos iso file name}/arch/boot/syslinux/isolinux
- /multiboot/${antergos iso file name}/arch/boot/syslinux
- /multiboot/${antergos iso file name}/isolinux

In one of them, there is a variable that is not correctly replaced, so if you change %INSTALATION_DIR% to "arch", it will load.

**Comment by mbusb** [comment]
You can directly boot from iso. Just copy iso to 'iso' directory and select
select boot from iso option using grub2.

**Comment by mbusb** [comment]
Fixed in the latest release version 9.2.0.
