### ISSUE TITLE
Multiboot freezes on 95% of extracting iso on ubuntu 17.04

### ISSUE THREAD

**Issue by opensas** [mbusb/multibootusb#208]
I formatted a usb 32 GB pen drive according to these instructions https://askubuntu.com/a/781236/26067

Then ran multibootusb, selected /dev/sdb1, and the iso linux-lite-3.6-64bit.iso

The UI froze at 95% with "Status: Extracting linux-lite-3.6-64bit.iso"

I'm running ubuntu 17.04

```
$ uname -a
Linux inspiron 4.10.0-35-generic #39-Ubuntu SMP Wed Sep 13 07:46:59 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

Any other information I could provide to solve this issue?

**Comment by lectrode** [comment]
When it is "frozen", can you open a Terminal and run ```sync```?
If ```sync``` hangs as well, that just means it's taking a while to transfer to the flash drive. It's not actually frozen. You'll need to wait for the transfer to finish before you can do anything else. It may take a while. I just tested writing a 4GB iso and it took about 20 minutes to write to a 16GB USB 2.0 flash drive.

Also, please make sure you look over the [User Guide](http://multibootusb.org/page_guide/) and the [FAQ](http://multibootusb.org/page_faq/) to ensure you are prepping the flash drive correctly.

If none of that works, can you [upload a log](http://multibootusb.org/page_faq/#where-is-multibootusb-log-file-located) so someone with better understanding of the issue can see what's getting stuck?

**Comment by mhohai** [comment]
Ubuntu 16.04 97% take more time, but it's work.

**Comment by mbusb** [comment]
@opensas 
Can you confirm if the issue still persist in new release? If yes then you must provide the log file....

**Comment by jgomo3** [comment]
I'm still waiting for the process to finish. I've waited for about 30 minutes.

I attached my log.
[multibootusb.log](https://github.com/mbusb/multibootusb/files/1572741/multibootusb.log)

**Comment by mbusb** [comment]
I can't find anything wrong in the log file. Can you issue **sync** command to see is syncing takes much time?

**Comment by jgomo3** [comment]
I just did it as suggested by this thread, and is still "working".

Also noticed that *lshw* hangs too, when displaying SCSI:

    $ sudo lshw
    SCSI

**Comment by mbusb** [comment]
I don't see anything wrong with the software here. Open the log file and issue the last 7zip command to check if the same issue appear again.

**Comment by jgomo3** [comment]
It extracts `.disk/**`, `EFI/**`, `README.diskdefines`, `boot/**` but when extracting `casper/**` it hangs on `casper/filesystem.size`:

    $ sudo 7z -ssc-  x -y -o"/mnt/multibootusb/lubuntu-17.10-desktop-amd64" "/home/jgomez/Downloads/lubuntu-17.10-desktop-amd64.iso"
    
    7-Zip [64] 9.20  Copyright (c) 1999-2010 Igor Pavlov  2010-11-18
    p7zip Version 9.20 (locale=en_US.UTF-8,Utf16=on,HugeFiles=on,1 CPU)
    
    Processing archive: /home/jgomez/Downloads/lubuntu-17.10-desktop-amd64.iso
    
    Extracting  .disk
    Extracting  .disk/base_installable
    Extracting  .disk/casper-uuid-generic
    Extracting  .disk/cd_type
    Extracting  .disk/info
    Extracting  .disk/release_notes_url
    Extracting  EFI
    Extracting  EFI/BOOT
    Extracting  EFI/BOOT/BOOTx64.EFI
    Extracting  EFI/BOOT/grubx64.efi
    Extracting  README.diskdefines
    Extracting  boot
    ### all the boot subdirectories ... including boot/grub
    Extracting  casper
    Extracting  casper/filesystem.manifest
    Extracting  casper/filesystem.manifest-remove
    Extracting  casper/filesystem.size

**Comment by jgomo3** [comment]
So it must be a problem with my device, I think.

I just tried to create a boot usb device with the Ubuntu Startup Creator and failed the same way.

Can I ask for help on diagnosing the device?

**Comment by mbusb** [comment]
My advice is to replace your USB disk. :-))
