### ISSUE TITLE
Kali linux 2017.2 i386 doesn't boot from QEMU — Unable to mount root FS

### ISSUE THREAD

**Issue by matclab** [mbusb/multibootusb#210]
multibootusb 8.8.0

Kali linux boot unde QEMU ends with a kernel panic : unable to mount root fs.

It works well on a real system.

**Comment by matclab** [comment]
Same probem on qemu with amd64 version.

**Comment by matclab** [comment]
I will close this issue as it seems not related to mutibootusb. 
Indeed the problem arise even when kali linux is installed on an USB key as recomended on the kali website (i.e without multibootusb).

**Comment by BurhanDanger** [comment]
https://wiki.archlinux.org/index.php/Syslinux#Limitations_of_UEFI_Syslinux
