### ISSUE TITLE
No GPT support?

### ISSUE THREAD

**Issue by JoshuaRLi** [mbusb/multibootusb#211]
As far as I have tested, the latest `multibootusb` release as of now does not support flash drives with GUID partition tables. DOS MBR works though. When will GPT support be released?

**Comment by mbusb** [comment]
Can you try the latest master or devel branch?

**Comment by JoshuaRLi** [comment]
@mbusb I will soon! Currently a little busy but I'll let you know.

**Comment by mbusb** [comment]
I have already released the newer version today. You can try that.

**Comment by mbusb** [comment]
The latest stable and devel branch support GPT.
