### ISSUE TITLE
Crash when selecting invalid ISO

### ISSUE THREAD

**Issue by Markus00000** [mbusb/multibootusb#212]
When selecting an invalid ISO (e.g. an unfinished download), the program crashes.

Version: 8.8.0

**Comment by alandmoore** [comment]
Problem seems to be that isodump3.ISO9660.__init__() doesn't check if the file has any data in it.  All it does is check if it can read the file, and if not, it crashes.  If it can, and the file is empty, it'll crash as soon as it tries to access bits.

@mbusb I can probably fix this, but I'm wondering where the best place to introduce some iso sanity checks would be.  isodump3 shouldn't `exit()` for sure, it should probably just raise exceptions, and mabye `iso.py` should catch these and send an error message up to the GUI?

Also, side note, isodump3.py has some very odd indentation.  Would it be ok for me to fix that?

**Comment by mbusb** [comment]
No issue in making pull request. But ensure that you do it on devel branch.

iso.py should be the file to modify.

**Comment by alandmoore** [comment]
I have a patch in the works.  The approach is to sanity check the selected .iso file in mbusb_gui.py using functions in iso.py and display a dialog error if the file has problems.  Sound good?  Not sure how the CLI interface will be affected, I can't see any calls to `ISO9660()` in it, so it seems isolated from the issue.

**Comment by mbusb** [comment]
Merged the pull request. Will test it later for cli...

**Comment by alandmoore** [comment]
I haven't made the pull request yet, but I'll do so now.
