### ISSUE TITLE
Feature Request: Selection Menu with all supported distributions listed for download

### ISSUE THREAD

**Issue by hellyberry** [mbusb/multibootusb#214]
Having to manually download the ISO-images frequently takes time and manual work.

Can a list of officially supported ISOs/distributions be implemented, along with URL for automatic download?

To simply mark with checkboxes which ISOs should go on the device, if still the latest checksum/date do not change, else update/install. This would make this tool a real time saver, too.

**Comment by mbusb** [comment]
I wont be implementing this feature. My internet speed is not so good for testing this feature. Sorry. At any case there is manual way to download.
