### ISSUE TITLE
suse RPM does not work with OpenSUSE

### ISSUE THREAD

**Issue by ncalero-uy** [mbusb/multibootusb#22]
Hello, just wanted to try it on OpenSUSE 13.2 and discovered that RPM install is not working well:

oraculo:/home/ncalero/Downloads # cat /etc/issue
Welcome to openSUSE 13.2 "Harlequin" - Kernel \r (\l).

oraculo:/home/ncalero/Downloads # uname -a
Linux oraculo.site 3.16.7-21-desktop #1 SMP PREEMPT Tue Apr 14 07:11:37 UTC 2015 (93c1539) x86_64 x86_64 x86_64 GNU/Linux

oraculo:/home/ncalero/Downloads # rpm -Uvh /home/ncalero/Downloads/multibootusb-7.5.0-1suse.noarch.rpm 
Preparing...                          ################################# [100%]
Updating / installing...
   1:multibootusb-7.5.0-1             ################################# [100%]

oraculo:/home/ncalero/Downloads # multibootusb 
Traceback (most recent call last):
  File "/usr/local/bin/multibootusb", line 33, in <module>
    from scripts.gui.ui_multibootusb import Ui_Dialog
ImportError: No module named scripts.gui.ui_multibootusb

But after downloading source and installing it with ./install.py, it is working:

oraculo:/home/ncalero/Downloads/multiboot/multibootusb-master # multibootusb 
Using PyUdev for detecting USB drives...
/dev/sdc1
syslinux.cfg does not exist for updating list widget.
syslinux.cfg does not exist for updating list widget.
Extracting syslinux to multibootusb directory...
Extracting syslinux 64 bit...
Extracting syslinux modules to multibootusb directory...
/usr/multibootusb/tools/syslinux/syslinux_modules.zip
Copying persistence data to multibootusb directory.
Bus::open: Can not get ibus-daemon's address. 
IBusInputContext::createInputContext: no connection to ibus-daemon 
Locating /run/media/ncalero/MULTIBOOT/multibootusb/syslinux.cfg
syslinux.cfg file not found...

Regards
Nelson

**Comment by mbusb** [comment]
The multibootusb package need not be installed. Just extract and run multibootusb script. Regarding the RPM package, It is the standard packaging done using python 'bdist_rpm' command.

**Comment by mbusb** [comment]
Use 'install.py' from source code.
