### ISSUE TITLE
Add support for openSuse Leap 42.3

### ISSUE THREAD

**Issue by mtausig** [mbusb/multibootusb#224]
Trying to add an ISO of openSuse Leap 42. 3 yields the error message

```
Sorry.
openSUSE-Leap-42.3-DVD-x86_64.iso is not supported at the moment.
Please email this issue to feedback.multibootusb@gmail.com
```
    
Requested informations:

* Host Operating system information (Linux/ Windows) and version: Ubuntu 16.04, 64 bit
* The ISO your are trying to create and ISO download link: openSUSE-Leap-42.3-DVD-x86_64.iso downloaded from http://download.opensuse.org/distribution/leap/42.3/iso/openSUSE-Leap-42.3-DVD-x86_64.iso
* USB disk information such as partition type, size, file system and so on: Samsung FIT, 64GB, trying to install on a 30GB FAT partition
* MultiBootUSB version you are using: 8.8.0

**Comment by mtausig** [comment]
## Update

With multibootusb 8.9.0, I get a different message:

```
The ISO sleceted is not supported at the moment.
You can try booting ISO using memdisk.
Distro can be uninstalled anytime from main menu.

Proceed with installation?
```
Selecting yes copies the iso file to the stick, but booting it doesn't work (it just returns to the boot menu after selecting the option)

**Comment by mbusb** [comment]
I am not sure why did the software detected as memdisk supported one. For
me it was detected as opensuse-install.

Can you provide me the link to download.

**Comment by mtausig** [comment]
> Can you provide me the link to download.

I updated the link in the OP.

**Comment by mbusb** [comment]
With latest release (9.1.0), you can simply copy open suse ISO to '/multibootusb/iso' directory and select 'scan and boot ISO ' option from grub2.

**Comment by mtausig** [comment]
Copying didn't work, because the ISO is too large for a FAT32 file system :-(
Also, there is no *scan and boot ISO* option in the boot manager. Do I have to do anything special to enable it?

I have also tried to use the netinstalltion ISO of opensuse (openSUSE-Leap-42.3-NET-x86_64.iso), that one could be booted if installed as a memdisk_iso.

**Comment by mbusb** [comment]
Open suse can be booted with version 9.1.0 and above using direct ISO method (simple copy ISO image in to '/multibootusb/iso' directory). Ensure that you are not using FAT filesystem as it has the limitation of storing less than 4 GB files.
