### ISSUE TITLE
Portable version for windows

### ISSUE THREAD

**Issue by mobtechpd** [mbusb/multibootusb#226]
Where i can download portable version for windows of multibootusb?

**Comment by mbusb** [comment]
Check out the source forge site at
https://sourceforge.net/projects/multibootusb/files/8.8.0/Windows/. I
removed the link  from main site because the size was large and very
difficult to debug the software.

**Comment by mbusb** [comment]
Can you confirm that if it works for you? If yes then I will close the issue.

**Comment by mobtechpd** [comment]
Works, tested on Windows 10 x64, thanks
