### ISSUE TITLE
QEMU not working under windows 7

### ISSUE THREAD

**Issue by unai-ndz** [mbusb/multibootusb#228]
[multibootusb.log](https://github.com/mbusb/multibootusb/files/1457883/multibootusb.log)
S.O: Windows 7 Pro SP1
MultiBootUSB Version 8.8.0
USB disk: NTFS(needed for the iso I am trying to boot)

It does not display any error message.

When I try to boot an ISO: 
`12:32:41.427 root INFO Executing ==> C:\Program Files (x86)\multibootusb\data\tools\qemu\qemu-system-x86_64.exe -boot d -cdrom F:\Sistemas-Operativos\medicat.17.04.01.stable-002.iso`

I noticed the missing quotes and tryed to run this:
`"C:\Program Files (x86)\multibootusb\data\tools\qemu\qemu-system-x86_64.exe" -boot d -cdrom F:\Sistemas-Operativos\medicat.17.04.01.stable-002.iso`
on a CMD command line. It works.

But when I try to boot the USB it shows this:
`12:32:48.880 root INFO Executing ==>  "C:\Program Files (x86)\multibootusb\data\tools\qemu\qemu-system-x86_64.exe" -L . -boot c -hda //./PhysicalDrive#2`
and that does nothing on CMD.
(Sometimes PhysicalDrive#1, depends on the devices attached)

Full log attached.

**Comment by mbusb** [comment]
This issue is fixed in the development version (on my system and yet to push it). 

Next version should fix this issue.

**Comment by unai-ndz** [comment]
That's nice. Thank you for this tool.
