### ISSUE TITLE
Distros freezing at splash screens

### ISSUE THREAD

**Issue by PirxGR** [mbusb/multibootusb#230]
Hello,
I am running Multiboot under Ubuntu 16.4 64x
I added several distros on default settings, with no error shown (see the screenshot), plus a modest persistence file for Ubuntu.
Now, Ubuntu boots nicely, but the rest of ditros gets frozen at their splash screens.
What am I missing?

![screenshot at 2017-11-13 10 01 55](https://user-images.githubusercontent.com/33618992/32715146-b49ce5cc-c859-11e7-938e-8954f7fe85be.png)

**Comment by PirxGR** [comment]
Sorry, the info about log file is included under "What should I do if I get a iso not supported error message?" which I did not check, as that's not my case. :)
I repeated the whole procedure to recreate logs.
[multibootusb.log](https://github.com/mbusb/multibootusb/files/1468702/multibootusb.log)

**Comment by PirxGR** [comment]
Bumping the topic.

**Comment by mbusb** [comment]
Thank for the bump :-)

Will get back to you later today.

**Comment by PirxGR** [comment]
Bump

**Comment by mbusb** [comment]
The log file seems to be ok. Is it under uefi boot?

**Comment by mbusb** [comment]
Please try the latest version. If syslinux boot does not work, try booting from GRUB boot menu. If the issue still persist, please open a new issue by referring this issue.
