### ISSUE TITLE
MBusb does not work with grml and persistence mode

### ISSUE THREAD

**Issue by fpusersuggest** [mbusb/multibootusb#232]
Hi,
I have successfully installed grml sysadmin live cd on a mbusb. The problem is it does not work with persicence mode. I mean... I successul install the iso with enabled persistence space. I boot and it works well... but all data saved on the  home directory goes to deletion after reboot.

**Comment by thrdroom** [comment]
This is a duplicate of #99

**Comment by mbusb** [comment]
Latest release version 9.2.0 has fixed this debian persistence issue. Please check it out.
