### ISSUE TITLE
8.9.0 crashes silently on Windows 10 (1709) when detecting usb devices

### ISSUE THREAD

**Issue by Honiix** [mbusb/multibootusb#234]
If Multibootusb 8.9.0 is running on Windows 10 (1709) and I plug a USB3 or USB2 stick in the computer and I click on "Detect Drives" a "Diskpart" windows pop-up and immediately this pop-up and Multibootusb disappears.

The log shows:
```
17:00:24.216 root INFO Running multibootusb version 8.9.0 from installed system...
17:00:24.306 root INFO Starting multibootusb GUI...
17:00:24.547 root INFO Cleaning old multibootusb directory...
17:00:24.551 root INFO Extracting syslinux to multibootusb directory...
17:00:24.635 root INFO Extracting syslinux modules to multibootusb directory...
17:00:25.833 root INFO No USB device found...
17:00:49.313 root INFO Selected device E:
```

If the USB stick is already pluged in, multibootusb never appear on screen.

**Comment by mbusb** [comment]
Will check it out...

**Comment by catterpiler74** [comment]
dosen't work on windows 10 same problem and same log

**Comment by Xaver2k** [comment]
Yes same here on windows 10... As soon as usb device is plugged in or as i press detect devices (when the usb device ist plugged in after multiboot start)...
For some seconds i can see a black terminal from c:/windows/system32/diskpart.exe, but then it shuts down

**Comment by clexanis** [comment]
Same here on Windows 10 1703.

**Comment by mbusb** [comment]
Tested the latest release version on two different windows 10 virtual Machine. It works perfectly fine. 

Can someone confirm the system language if it is different from English?

**Comment by Xaver2k** [comment]
My system language is german.

**Comment by mbusb** [comment]
What is the output of diskpart.exe with admin rights?

**Comment by Xaver2k** [comment]
If it gets open by multiboot, it stays black with no text, then closes

**Comment by Honiix** [comment]
When I first encounter the problem, Windows was in english. Now it's in french but have the same problem. Here is an output of Diskpart with admin rigths:
```Microsoft DiskPart version 10.0.16299.15

Copyright (C) Microsoft Corporation.
Sur l’ordinateur : HYPERION

DISKPART> list disk

  N° disque  Statut         Taille   Libre    Dyn  GPT
  ---------  -------------  -------  -------  ---  ---
  Disque 0    En ligne        931 G octets      0 octets
  Disque 1    En ligne        465 G octets  1024 K octets
  Disque 2    En ligne       1863 G octets      0 octets        *
  Disque 3    En ligne         14 G octets      0 octets```

**Comment by mbusb** [comment]
Probably this could be the issue. Because the code written searches for the name 'Disk' from the diskpart.exe output. I will redo the code and test it...

**Comment by IAmRusab** [comment]
I confirm this problem also for me. W10 1709 64bit. App works without memorysticks. When I plug it - app is disappearing...

**Comment by mbusb** [comment]
Fixed in the latest commit. Should not have problem in next release.

**Comment by Tajnymag** [comment]
Still happening..

```
11:42:51.333 root INFO Running multibootusb version 9.0.0 from installed system...
11:42:51.733 root INFO Starting multibootusb GUI...
11:42:52.431 root INFO Extracting syslinux to multibootusb directory...
11:42:53.411 root INFO Extracting syslinux modules to multibootusb directory...
11:42:54.760 root INFO No USB device found...
11:43:48.752 root INFO Selected device D:
11:43:52.173 root INFO b'Name               Type                     \r\r\nDisk #3, odd\xa1l #0  Unknown                  \r\r\nDisk #0, odd\xa1l #0  Installable File System  \r\r\nDisk #0, odd\xa1l #1  Installable File System  \r\r\nDisk #0, odd\xa1l #2  Unknown                  \r\r\nDisk #0, odd\xa1l #3  Installable File System  \r\r\nDisk #1, odd\xa1l #0  Installable File System  \r\r\n\r\r\n'
11:44:04.593 root INFO Running multibootusb version 9.0.0 from installed system...
11:44:04.846 root INFO Starting multibootusb GUI...
11:44:04.911 root INFO Cleaning old multibootusb directory...
11:44:04.913 root INFO Extracting syslinux to multibootusb directory...
11:44:05.300 root INFO Extracting syslinux modules to multibootusb directory...
11:44:05.968 root INFO Selected device D:
11:44:07.469 root INFO b'Name               Type                     \r\r\nDisk #3, odd\xa1l #0  Unknown                  \r\r\nDisk #0, odd\xa1l #0  Installable File System  \r\r\nDisk #0, odd\xa1l #1  Installable File System  \r\r\nDisk #0, odd\xa1l #2  Unknown                  \r\r\nDisk #0, odd\xa1l #3  Installable File System  \r\r\nDisk #1, odd\xa1l #0  Installable File System  \r\r\n\r\r\n'
11:51:07.340 root INFO Running multibootusb version 9.0.0 from installed system...
11:51:07.604 root INFO Starting multibootusb GUI...
11:51:07.672 root INFO Cleaning old multibootusb directory...
11:51:07.674 root INFO Extracting syslinux to multibootusb directory...
11:51:08.046 root INFO Extracting syslinux modules to multibootusb directory...
11:51:08.689 root INFO Selected device D:
```

**Comment by jidea** [comment]
New user here. i have the same problem with last version. i have french version of windows 10. 
after readingissues i use version 8.8.0 that don't crash.

**Comment by mbusb** [comment]
OK. Will check today.

**Comment by mbusb** [comment]
Please [download](https://drive.google.com/open?id=1pBQNMbuLuvJwQ7q5nvThg1VpfKjOfmTc) the yet to be released setup file. If someone can confirm that it fixes the issue then I will go ahead and release it to public download.

**Comment by Tajnymag** [comment]
Confirming that the 9.0.1 release is not crashing on czech version of Windows. :)

**Comment by mbusb** [comment]
OK. Will release it tomorrow as I am already in bed.

**Comment by Honiix** [comment]
Confirming that 9.0.1 works on french version of Windows too. 

Many thanks for your great work! I look forward to use that very useful tool!

**Comment by mbusb** [comment]
It works on my system and other users. Closing the issue.
