### ISSUE TITLE
Bad package warning

### ISSUE THREAD

**Issue by ElToro1966** [mbusb/multibootusb#236]
I get a bad package warning when trying to install the latest deb-package via the software center on Ubuntu 14.04 LTS:
Lintian check results for /tmp/mozilla_eric0/python3-multibootusb_8.9.0-1_all-1.deb:
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/acpi.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/adler32.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/affs.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/afs.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/ahci.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/all_video.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/aout.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/archelp.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/at_keyboard.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/ata.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/backtrace.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/bfs.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/biosdisk.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/bitmap.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/bitmap_scale.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/blocklist.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/boot.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/bsd.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/bswap_test.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/btrfs.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/bufio.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/cat.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/cbfs.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/cbls.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/cbmemc.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/cbtable.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/cbtime.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/chain.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/cmdline_cat_test.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/cmosdump.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/cmostest.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/cmp.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/cmp_test.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/configfile.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/cpio.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/cpio_be.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/cpuid.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/crc64.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/crypto.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/cryptodisk.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/cs5536.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/ctz_test.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/date.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/datehook.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/datetime.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/disk.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/diskfilter.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/div.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/div_test.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/dm_nv.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/drivemap.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/echo.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/efiemu.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/ehci.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/elf.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/eval.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/exfat.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/exfctest.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/ext2.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/extcmd.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/fat.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/file.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/font.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/freedos.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/fshelp.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/functional_test.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/gcry_arcfour.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/gcry_blowfish.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/gcry_camellia.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/gcry_cast5.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/gcry_crc.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/gcry_des.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/gcry_dsa.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/gcry_idea.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/gcry_md4.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/gcry_md5.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/gcry_rfc2268.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/gcry_rijndael.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/gcry_rmd160.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/gcry_rsa.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/gcry_seed.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/gcry_serpent.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/gcry_sha1.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/gcry_sha256.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/gcry_sha512.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/gcry_tiger.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/gcry_twofish.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/gcry_whirlpool.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/gdb.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/geli.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/gettext.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/gfxmenu.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/gfxterm.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/gfxterm_background.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/gfxterm_menu.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/gptsync.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/gzio.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/halt.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/hashsum.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/hdparm.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/hello.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/help.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/hexdump.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/hfs.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/hfsplus.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/hfspluscomp.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/http.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/iorw.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/iso9660.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/jfs.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/jpeg.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/keylayouts.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/keystatus.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/ldm.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/legacy_password_test.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/legacycfg.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/linux.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/linux16.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/loadenv.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/loopback.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/ls.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/lsacpi.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/lsapm.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/lsmmap.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/lspci.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/luks.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/lvm.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/lzopio.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/macbless.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/macho.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/mda_text.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/mdraid09.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/mdraid09_be.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/mdraid1x.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/memdisk.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/memrw.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/minicmd.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/minix.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/minix2.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/minix2_be.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/minix3.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/minix3_be.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/minix_be.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/mmap.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/morse.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/mpi.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/msdospart.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/mul_test.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/multiboot.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/multiboot2.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/nativedisk.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/net.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/newc.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/nilfs2.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/normal.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/ntfs.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/ntfscomp.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/ntldr.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/odc.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/offsetio.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/ohci.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/part_acorn.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/part_amiga.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/part_apple.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/part_bsd.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/part_dfly.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/part_dvh.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/part_gpt.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/part_msdos.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/part_plan.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/part_sun.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/part_sunpc.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/parttool.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/password.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/password_pbkdf2.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/pata.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/pbkdf2.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/pbkdf2_test.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/pci.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/pcidump.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/plan9.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/play.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/png.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/priority_queue.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/probe.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/procfs.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/progress.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/pxe.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/pxechain.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/raid5rec.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/raid6rec.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/random.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/read.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/reboot.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/regexp.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/reiserfs.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/relocator.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/romfs.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/scsi.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/search.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/search_fs_file.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/search_fs_uuid.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/search_label.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/sendkey.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/serial.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/setjmp.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/setjmp_test.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/setpci.mod
E: python3-multibootusb: arch-independent-package-contains-binary-or-object usr/share/multibootusb/data/multibootusb/grub/i386-pc/sfs.mod

**Comment by mbusb** [comment]
You will get those warning. Because, lot of binary packages which are
necessary for successful operation of the application is included in the
package.
This question was asked before. My advice is that if you are so worried,
you can run the application directly from source.
