### ISSUE TITLE
MultiBoot command line "TypeError: Can't convert 'bool' object to str implicitly"

### ISSUE THREAD

**Issue by ProGentle** [mbusb/multibootusb#237]
I try to run MultiBoot from command line. And it drops out everytime with the follwing error: "TypeError: Can't convert 'bool' object to str implicitly". Any idea what could be the problem? 

BTW.: The GUI is working with the same USB stick and ISO.

Thanks a lot
Matthias

<pre>
# multibootusb -y -c -i  systemrescuecd-x86-5.1.2.iso  -t /dev/sdg1 
Running multibootusb version 8.9.0 from installed system...
Starting multibootusb from Command line...
25008
True
Cleaning old multibootusb directory...
Syslinux exist in multibootusb directory...
Executing ==> 7z -ssc-  x -y "systemrescuecd-x86-5.1.2.iso" -o/root/.multibootusb/iso_cfg_ext_dir "*.cfg" -r 2> /dev/null
Executing ==> 7z -ssc-  x -y "systemrescuecd-x86-5.1.2.iso" -o/root/.multibootusb/iso_cfg_ext_dir "*.txt" -r 2> /dev/null
Executing ==> 7z -ssc-  x -y "systemrescuecd-x86-5.1.2.iso" -o/root/.multibootusb/iso_cfg_ext_dir "*isolinux.bin" -r 2> /dev/null
Executing ==> 7z -ssc-  x -y "systemrescuecd-x86-5.1.2.iso" -o/root/.multibootusb/iso_cfg_ext_dir "*.lst" -r 2> /dev/null
Initiating installation process for systemrescuecd-x86-5.1.2
Detected distro type is    :systemrescuecd

Selected ISO is          :"systemrescuecd-x86-5.1.2.iso"
Selected target device is  :"/dev/sdg1"
Skipping user confirmation for systemrescuecd-x86-5.1.2.iso
Copying multibootusb directory to /media/progent/MULTIBOOT02
EFI/BOOT directory does not exist. Creating new.
Copying EFI directory to /media/progent/MULTIBOOT02
Installing systemrescuecd-x86-5.1.2.iso on /media/progent/MULTIBOOT02/multibootusb/systemrescuecd-x86-5.1.2                                             |
Executing ==> 7z -ssc-  x -y -o"/media/progent/MULTIBOOT02/multibootusb/systemrescuecd-x86-5.1.2" "systemrescuecd-x86-5.1.2.iso" 2> /dev/null
ISO extracted successfully. Sync is in progress...######################################################################################################|

Found syslinux version 4

Executing ==> /root/.multibootusb/syslinux/bin/syslinux4 -i -d "/multibootusb/systemrescuecd-x86-5.1.2/isolinux" /dev/sdg1

Syslinux install on distro directory is successful...

Executing ==> dd if=/dev/sdg1 of="/media/progent/MULTIBOOT02/multibootusb/systemrescuecd-x86-5.1.2/isolinux/systemrescuecd.bs" count=1

1+0 Datensätze ein
1+0 Datensätze aus
512 bytes copied, 0,00477895 s, 107 kB/s

Bootsector copy is successful...

Traceback (most recent call last):
  File "/usr/bin/multibootusb", line 188, in <module>
    cli_install_distro()
  File "/usr/lib/python3/dist-packages/scripts/mbusb_cli.py", line 69, in cli_install_distro
    iso_install(config.image_path)
  File "/usr/lib/python3/dist-packages/scripts/mbusb_cli.py", line 114, in iso_install
    syslinux_default(config.usb_disk)
  File "/usr/lib/python3/dist-packages/scripts/syslinux.py", line 103, in syslinux_default
    mbr_install_cmd = 'dd bs=440 count=1 conv=notrunc if=' + mbr_bin + ' of=' + usb_disk[:-1]
TypeError: Can't convert 'bool' object to str implicitly
</pre>

**Comment by mbusb** [comment]
Is the same issue persist when you use gui? I suspect that gpt disk
checking is not included in cli.

**Comment by mbusb** [comment]
Oops, I didn't read your first post properly. 

I assume that it works properly in gui. Will push new commit soon.

**Comment by mbusb** [comment]
Fixed in the devel branch.

**Comment by ProGentle** [comment]
Hi,

tested it again with the devel branch but no luck. Same error. See below
GUI is still working.

BTW.: I try to find the differences between master and devel branch but could not really find some. Is it possible that the wrong files are in the zip?

Matthias


<pre>
# ./multibootusb -y -c -i  ../systemrescuecd-x86-5.1.2.iso  -t /dev/sdg1
Running multibootusb version 8.9.0 from source...
Starting multibootusb from Command line...
25008
True
/media/root/MBOOTGPT
Cleaning old multibootusb directory...
Syslinux exist in multibootusb directory...
Executing ==> 7z -ssc-  x -y "../systemrescuecd-x86-5.1.2.iso" -o/root/.multibootusb/iso_cfg_ext_dir "*.cfg" -r 2> /dev/null
Executing ==> 7z -ssc-  x -y "../systemrescuecd-x86-5.1.2.iso" -o/root/.multibootusb/iso_cfg_ext_dir "*.txt" -r 2> /dev/null
Executing ==> 7z -ssc-  x -y "../systemrescuecd-x86-5.1.2.iso" -o/root/.multibootusb/iso_cfg_ext_dir "*isolinux.bin" -r 2> /dev/null
Executing ==> 7z -ssc-  x -y "../systemrescuecd-x86-5.1.2.iso" -o/root/.multibootusb/iso_cfg_ext_dir "*.lst" -r 2> /dev/null
Initiating installation process for systemrescuecd-x86-5.1.2
Detected distro type is    :systemrescuecd

Selected ISO is          :"systemrescuecd-x86-5.1.2.iso"
Selected target device is  :"/dev/sdg1"
Skipping user confirmation for ../systemrescuecd-x86-5.1.2.iso
Copying multibootusb directory to /media/root/MBOOTGPT
EFI/BOOT directory does not exist. Creating new.
Copying EFI directory to /media/root/MBOOTGPT
Installing systemrescuecd-x86-5.1.2.iso on /media/root/MBOOTGPT/multibootusb/systemrescuecd-x86-5.1.2                                                 |
Executing ==> 7z -ssc-  x -y -o"/media/root/MBOOTGPT/multibootusb/systemrescuecd-x86-5.1.2" "../systemrescuecd-x86-5.1.2.iso" 2> /dev/null
ISO extracted successfully. Sync is in progress...##################################################################################################  |
100% |################################################################################################################################################|
Found syslinux version 4

Executing ==> /root/.multibootusb/syslinux/bin/syslinux4 -i -d "/multibootusb/systemrescuecd-x86-5.1.2/isolinux" /dev/sdg1

Syslinux install on distro directory is successful...

Executing ==> dd if=/dev/sdg1 of="/media/root/MBOOTGPT/multibootusb/systemrescuecd-x86-5.1.2/isolinux/systemrescuecd.bs" count=1

1+0 Datensätze ein
1+0 Datensätze aus
512 bytes copied, 0,00501229 s, 102 kB/s

Bootsector copy is successful...

Traceback (most recent call last):
  File "./multibootusb", line 188, in <module>
    cli_install_distro()
  File "/home/progent/tmp/multibootusb-devel/scripts/mbusb_cli.py", line 69, in cli_install_distro
    iso_install(config.image_path)
  File "/home/progent/tmp/multibootusb-devel/scripts/mbusb_cli.py", line 114, in iso_install
    syslinux_default(config.usb_disk)
  File "/home/progent/tmp/multibootusb-devel/scripts/syslinux.py", line 103, in syslinux_default
    mbr_install_cmd = 'dd bs=440 count=1 conv=notrunc if=' + mbr_bin + ' of=' + usb_disk[:-1]
TypeError: Can't convert 'bool' object to str implicitly
</pre>

**Comment by mbusb** [comment]
Oops, looks like I have not uploaded the commit. Will do that today.

**Comment by ProGentle** [comment]
Testing devel => same error as before
Testing master => no error message

Looks like devel and master are out of sync but master is working.

Thanks for the quick repair and the cool software
Matthias

**Comment by mbusb** [comment]
Since it was an important bug I pushed directly to master.
