### ISSUE TITLE
8.9.0 does not launch on Linux

### ISSUE THREAD

**Issue by nerijus** [mbusb/multibootusb#238]
8.8.0 works, while 8.9.0:
```
Traceback (most recent call last):
  File "/usr/local/bin/multibootusb", line 164, in <module>
    if config.debug is True:
NameError: name 'config' is not defined
```

**Comment by mbusb** [comment]
Linux is not a distro. Which distro are you using?

**Comment by nerijus** [comment]
Fedora 26, 27.

**Comment by mbusb** [comment]
Looks like the application was installed in python version 2 instead of
version 3. What happen when you run from source using python3?

**Comment by nerijus** [comment]
I used rpms - multibootusb-8.8.0-1.noarch.rpm and multibootusb-8.9.0-1.noarch.rpm. They have /usr/local/lib/python3.4 and /usr/local/lib/python3.5 inside (although Fedora 26/27 has python3-3.6.3).

Running from source works, but it would be nice to make rpm work too.

**Comment by mbusb** [comment]
Will check it out from my side.

**Comment by Pedro-MC** [comment]
I'm having the same issue in a Mageia 5 system. Some system info follows.

$ Linux ws0 4.4.92-desktop-1.mga5 #1 SMP Thu Oct 12 20:14:45 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
$ cat /etc/release 
Mageia release 5 (Official) for x86_64
$ rpm -q multibootusb
multibootusb-8.9.0-1
$ /usr/bin/python3 -V
Python 3.4.3

**Comment by mbusb** [comment]
The latest release was build using Debian stretch and python version available is version 3.5. I suspect that the libs are installed at python 3.5 lib path and you have only python 3.4 installed. I think this is the issue and hopefully I should fix it in next release.

**Comment by nerijus** [comment]
Fedora 26 has python3-3.6.3-2.fc26.x86_64, but nevertheless multibootusb-8.8.0-1.noarch.rpm works here, although it has /usr/local/lib/python3.4/ inside.

**Comment by mbusb** [comment]
Because multibootusb modifies the system path to include python 3.4 lib
path. I have already done the coding and hopefully will release it this
weekend.

**Comment by mbusb** [comment]
Please test the latest master. I have already applied the patch.

**Comment by Pedro-MC** [comment]
Tested latest master and at least here the issue is resolved. Thanks.

**Comment by ramesh45345** [comment]
Unfortunately master (67f57a8) is not working on Fedora 27, with the same error message:
```
$ multibootusb
Traceback (most recent call last):
  File "/usr/local/bin/multibootusb", line 174, in <module>
    if config.debug is True:
NameError: name 'config' is not defined
```
This was tested from git source, after running `./install.py`. When I ran `python3 -v ./multibootusb`, it looks like the as-written imports were successful. Is an import missing or something? Not sure in what script the config variable was set...

System Info:
```
$ uname -a
Linux Hostname 4.14.7-300.fc27.x86_64 #1 SMP Mon Dec 18 16:06:12 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
$ cat /etc/release
Fedora release 27 (Twenty Seven)
$ /usr/bin/python3 -V
Python 3.6.3
```

**Comment by mbusb** [comment]
I am pretty sure that multibootusb have installed at python2 lib directory. The next release (rpm) should fix this. Hopefully within two or thee days.

**Comment by ramesh45345** [comment]
I do not believe this has to do with python2, all my commands were run with python3. Furthermore, it happens on master, so I don't think a new release will simply solve the problem. Just to verify, I re-ran the installer, and noted that it is installing to /usr/local/lib/python3.6. Full install and run log is here: [install_log.txt](https://github.com/mbusb/multibootusb/files/1593655/install_log.txt)

**Comment by mbusb** [comment]
Believe me, it will work with new rpm package. The issue is due to path which has been corrected in the master branch. Tested personnel y by me before commenting here. 

By the way did you remove your old multibootusb install? Also try only from source without using install.py script.

**Comment by ramesh45345** [comment]
Whoops, you are right, it is working. My problem was that I had uninstalled the dependencies (python3-qt5, etc) when I removed the RPM to test from source. After reinstalling the RPM and running git master from source it works. Sorry for the confusion.

**Comment by mbusb** [comment]
Its ok man.

**Comment by nerijus** [comment]
9.0.0 works on Fedora, thanks a lot!
