### ISSUE TITLE
Badly detected linux type.

### ISSUE THREAD

**Issue by Dani3I** [mbusb/multibootusb#240]
I downloaded the "slacko puppy" system from the official forum page ( [slacko64-6.9.6.4-uefi](http://murga-linux.com/puppy/viewtopic.php?t=108017) ) but when I choose it, the wrong type of operating system is displayed ("zenwalk" is displayed but it should be "puppy").
![zenwalk](https://user-images.githubusercontent.com/34142462/33456032-5837a970-d61e-11e7-97a1-27a55f85485b.png)

After installation and trying to run (as you might expect) is an error.

However, "Artful Puppy" ( [ArtfulPup-17.11](http://murga-linux.com/puppy/viewtopic.php?t=111735) ) works correctly.
![puppy](https://user-images.githubusercontent.com/34142462/33456040-5e64db2e-d61e-11e7-9386-44b5dc16f7a2.png)

Is it possible to choose the type of system manually or to fix the error?

Sorry for my bad English.

**Comment by mbusb** [comment]
You can't change the distro type manually. Will test it with the ISO. 

I have a plan to make multibootusb plugin enabled. So that user can use a text file to specify distro specific options. But I can't guarantee the implementation time frame.

**Comment by Dani3I** [comment]
I have tested ISO and it is correct but when I run it from a pen drive made by multibootusb, this message is displayed: 
![wp_20171202_17_01_00_rich](https://user-images.githubusercontent.com/34142462/33517449-ae5eee50-d784-11e7-962b-1b90344ce521.jpg)

**Comment by mbusb** [comment]
The issue has been solved in the latest devel branch commit. Will release the new version soon.

**Comment by mbusb** [comment]
Fixed in the latest release. Closing the issue.
