### ISSUE TITLE
Parted Magic on UEFI - Wrong paths in grub.cfg

### ISSUE THREAD

**Issue by gabrielmagno** [mbusb/multibootusb#244]
I tried loading a Parted Magic (version 2017_09_05) image through UEFI, but got an error when loading the kernel.
I've noticed that the path was the original from the pmagic iso (`/pmagic/bzImage64`) instead of the path considering multibootusb (`/multibootusb/pmagic_2017_09_05/pmagic/bzImage64`).

I've manually edited the grub.cfg file (`/multibootusb/pmagic_2017_09_05/pmagic/boot/grub/grub.cfg`) to consider the multibootusb path. Also, I had to include the "directory" variable in the settings variable for loading the kernel.

In this [gist](https://gist.github.com/gabrielmagno/e79febc3da29e4662ff9c08adcffee33), I show 3 files that I think might help fix the problem:
- `grub-ORIGINAL.cfg` : the file that comes with the pmagic.iso
- `grub-ERROR.cfg` : the file that multibootusb creates when including the pmagic image
- `grub-FIXED.cfg` : the file that I manually edited from grub-ERROR.cfg , and that made pmagic load fine

**Comment by mbusb** [comment]
Thanks for the correcting the issue. Made necessary changes in the local devel branch. Would push to remote later.

**Comment by mbusb** [comment]
Latest pull request fixes the issue. Closing the issue.
