### ISSUE TITLE
multiboot-pkexec won't launch multiboot after updating to 8.9.0

### ISSUE THREAD

**Issue by gabrc52** [mbusb/multibootusb#247]
Output:

```
Running multibootusb version 8.9.0 from installed system...
Starting multibootusb GUI...
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
qt.qpa.screen: QXcbConnection: Could not connect to display 
Could not connect to any X display.

```

This is on Manjaro using the AUR package.

Meanwhile manually granting root access will do.

**Comment by mbusb** [comment]
This is nothing to do with multibootusb. This is the issue with the way distro setting the **XDG_RUNTIME_DIR** variable. It is normally set to **/run/user/1000** as a normal user. If you execute using pkexec, the same path is supposed to change to **/run/user/0** which is not happening in your case. Anyway, the workaround is to use **kdesu** or **sudo**  for launching the application.

**Comment by mbusb** [comment]
Closing the issue.
