### ISSUE TITLE
Missing dependency on debian:8.10 vanilla

### ISSUE THREAD

**Issue by eaglerainbow** [mbusb/multibootusb#249]
**Prio low**

For testing in #242 I had created a small environment using docker, whose `Dockerfile` reads like this:
```
FROM debian:8.10

RUN apt-get update && apt-get -y install mc jed less python3 git \
  python3-pyqt5 parted util-linux mtools python3-dbus python3-pyudev \
  p7zip-full python3-six
```
Running then the docker image with `/bin/bash` I issued the following set of commands:
```
cd && git clone https://github.com/mbusb/multibootusb.git && cd multibootusb
```
Current state of branch `master` (which is checked out here) is https://github.com/mbusb/multibootusb/commit/67f57a8d889dc4abf56cbf75ffcaf531941a271b, which is roughly 8.9.0.

Trying then to run multibootusb, the following error message is issued:
```
root@cf058091d456:~/multibootusb# python3 ./multibootusb
Traceback (most recent call last):
  File "./multibootusb", line 174, in <module>
    if config.debug is True:
NameError: name 'config' is not defined
```

Please note that ```python3 -V``` states
```
Python 3.4.2
```

The same result is also provided when changing the underlying operating system version from `debian:8.10` to `ubuntu:16.04`. There, Python 3.5.x is running. 

**Problem statement**
There seems to be "some additional" dependency necessary, which is not documented properly in the `README.md`. Yet, the dependencies `python3-pyqt5 parted util-linux mtools python3-dbus python3-pyudev p7zip-full python3-six` I copied out from the manifest file of the current `.deb` package. I would have expected that these dependencies would also be mentioned as prerequisites to the section "Installation" -> "On Linux" -> "Using source code method". 

**Additional Information**
Could be related to #238, but that's unclear.

**Comment by klopsi** [comment]
Not sure what dependency would fix this.

I first installed https://github.com/mbusb/multibootusb/releases/download/v9.1.0/python3-multibootusb_9.1.0-1_all.deb

Running this yielded the error:
Traceback (most recent call last):
  File "./multibootusb", line 174, in <module>
    if config.debug is True:
NameError: name 'config' is not defined

By my primitive python understanding, the "from scripts import config (and gen) isn't working.

I tried adding 
    sys.path.append('/home/klopsi/Downloads/multiboot/multibootusb/scripts/') to expllicitly load the scripts in the multibootusb git repo, but same errors.

**Comment by mbusb** [comment]
@klopsi  Remove your old install. Install again deb package and let me know the terminal output of `ls \usr\lib\python3\dist-packages\scripts\`.
