### ISSUE TITLE
file not found error during iso installation

### ISSUE THREAD

**Issue by Dorifer** [mbusb/multibootusb#250]
ran into a previously not encountered error while trying to install an iso:

>

>  dorifer@e135:~$
> 
>  sudo multibootusb
> Running multibootusb version 9.0.0 from source...
> Starting multibootusb GUI...
> QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
> Cleaning old multibootusb directory...
> Syslinux exist in multibootusb directory...
> Using pyudev for detecting USB drives...
> 	/dev/sdb
> 	/dev/sdb1
> 	/dev/sdb2
> Selected device /dev/sdb
> Device /dev/sdb is a MBR disk...
> USB disk is not mounted and can't update list widget...
> Executing ==> 7z -ssc-  x -y "/home/dorifer/Downloads/kali-linux-light-2017.3-amd64/kali-linux-light-2017.3-amd64.iso" -o/root/.multibootusb/iso_cfg_ext_dir "*.cfg" -r 2> /dev/null
> Executing ==> 7z -ssc-  x -y "/home/dorifer/Downloads/kali-linux-light-2017.3-amd64/kali-linux-light-2017.3-amd64.iso" -o/root/.multibootusb/iso_cfg_ext_dir "*.txt" -r 2> /dev/null
> Executing ==> 7z -ssc-  x -y "/home/dorifer/Downloads/kali-linux-light-2017.3-amd64/kali-linux-light-2017.3-amd64.iso" -o/root/.multibootusb/iso_cfg_ext_dir "*isolinux.bin" -r 2> /dev/null
> Executing ==> 7z -ssc-  x -y "/home/dorifer/Downloads/kali-linux-light-2017.3-amd64/kali-linux-light-2017.3-amd64.iso" -o/root/.multibootusb/iso_cfg_ext_dir "*.lst" -r 2> /dev/null
> Persistence option is available.
> Persistence Max Size: Unknown
> Selected USB is a disk. Please select a disk partition from the drop down list
> Selected device /dev/sdb1
> Device /dev/sdb1 is a MBR disk...
> MultiBoot Install: USB Disk: /dev/sdb1
> MultiBoot Install: USB Label: NUBSI
> MultiBoot Install: USB UUID: 5ACA-00CD
> MultiBoot Install: USB mount path: /run/media/dorifer/NUBSI
> MultiBoot Install: Disk total size: 5.9G
> MultiBoot Install: Disk used size: 14.3M
> MultiBoot Install: Disk free size: 5.9G
> MultiBoot Install: Filesystem: vfat
> MultiBoot Install: Disk vendor: Kingston
> MultiBoot Install: Disk model: DataTraveler_3.0
> MultiBoot Install: ISO file: kali-linux-light-2017.3-amd64.iso
> MultiBoot Install: Distro type detected: debian-install
> Persistence chosen is 0B
> multibootusb directory already exists. Not copying.
> EFI directory already exist. Not copying.
> New EFI modules does not exist. Copying now.
> Traceback (most recent call last):
>   File "/usr/lib/python3.6/site-packages/scripts/mbusb_gui.py", line 552, in onCreateClick
>     copy_mbusb_dir_usb(config.usb_disk)
>   File "/usr/lib/python3.6/site-packages/scripts/gen.py", line 252, in copy_mbusb_dir_usb
>     os.path.join(usb_mount_path, 'multibootusb', 'grub', 'x86_64-efi'))
>   File "/usr/lib/python3.6/shutil.py", line 309, in copytree
>     names = os.listdir(src)
> FileNotFoundError: [Errno 2] Datei oder Verzeichnis nicht gefunden: '/usr/share/multibootusb/data/multibootusb/grub/x86_64-efi'
> Abgebrochen

**Comment by mbusb** [comment]
Releasing new version today. That should fix this.

**Comment by Dorifer** [comment]
awesome!

**Comment by mbusb** [comment]
New version is released.

**Comment by mbusb** [comment]
Ensure that you remove old install before installing latest one. Closing the issue now.
