### ISSUE TITLE
Install Syslinux button does nothing

### ISSUE THREAD

**Issue by Electronics** [mbusb/multibootusb#254]
Multiple windows machines running windows 10 pro 1709, none of the buttons on the syslinux tab do anything. If the drive is unplugged and the install button is clicked, the program closes.

**Comment by Shensueru** [comment]
Both in Windows 10 pro 1709 and in Linux Kubuntu 17.10 as soon as the program tries to write Syslinux stops responding. If the drive is plugged, the installation succeeds but as soon as syslinux is installed the program closes. I repeat both on linux and windows

**Comment by mbusb** [comment]
Will check it out.

**Comment by mbusb** [comment]
Commit https://github.com/mbusb/multibootusb/commit/3136ffe4fa38e570f72fb032184273eaae325434 fixes this issue.

**Comment by kelfka** [comment]
Same problem here. The software crashes when it tries to install syslinux. Either when I try to install it manually or when it tries when installing a distribution.  I downloaded all the files from Commit 3136ffe and replaced the old ones. The software says it's now at version 9.2 but I still got the same problem. Was there an other way to update the software?

**Comment by mbusb** [comment]
This bug has been fixed in the latest release version 9.2.0. So closing it now.
