### ISSUE TITLE
why kvm is not enabled in qemu?

### ISSUE THREAD

**Issue by masavini** [mbusb/multibootusb#255]
running multibootusb 9.1.0...
qemu was horrendously slow until i added `-enable-kvm` option to qemu commands in `qemu.py`.

i'm a total newbie, so i was wondering why it is not set by default...

**Comment by mbusb** [comment]
Will do that.

**Comment by masavini** [comment]
`qemu.py`

line 51:
```
cmd = qemu + ram + ' -boot d' + ' -cdrom "' + str(qemu_iso_link) + '"'
cmd = qemu + ' -enable-kvm' + ram + ' -boot d' + ' -cdrom "' + str(qemu_iso_link) + '"'
```

line 101:
```
cmd = qemu + ' -hda "' + qemu_usb_disk + '"' + ram + ' -vga std'
cmd = qemu + ' -enable-kvm' + ' -hda "' + qemu_usb_disk + '"' + ram + ' -vga std'
```

i guess line 91 should be edited as well, but i have no windows machine to test it...

**Comment by mbusb** [comment]
The windows binaries are little older. I need to test it before making a
commit.

**Comment by mbusb** [comment]
Added kvm for qemu under Linux on latest devel branch.

**Comment by mbusb** [comment]
Latest release 9.2.0 has been released with this feature.
