### ISSUE TITLE
Application crashes when both disk and image are selected if the disk is not yet mounted

### ISSUE THREAD

**Issue by Evanjs** [mbusb/multibootusb#271]
Upon selecting an ISO and USB disk, if the disk I selected is an unmounted partition, the application crashes.  Here is the relevant traceback.
I was able to remedy this by checking if `usb.details(config.usb_disk)['mount_point'] == 'No_Mount'` in mbusb_gui.py > `ui_update_persistence` and returning from `ui_update_persistence` if it does.

Not too familiar with the error handling in this app and didn't want to muck things up so I held off on a PR (will try to make one next time :stuck_out_tongue: )
```
Traceback (most recent call last):
  File "/usr/lib64/python3.6/site-packages/scripts/mbusb_gui.py", line 268, in browse_iso
    self.ui_update_persistence()
  File "/usr/lib64/python3.6/site-packages/scripts/mbusb_gui.py", line 285, in ui_update_persistence
    self.ui.slider_persistence.setMaximum(config.persistence_max_size / 1024 / 1024)
TypeError: unsupported operand type(s) for /: 'str' and 'int'
Aborted (core dumped)
```

Currently running Gentoo Linux (4.15.3).  Default Python version is 3.6.4.

**Comment by Evanjs** [comment]
Did not realize this application does not support exFAT.  This might be a non-issue per the specification, in that case, as I initially saw this when trying to use an exFAT drive/partition.

**Comment by mbusb** [comment]
You have found the solution yourself. Try formating to FAT and use multibootusb.
