### ISSUE TITLE
Invalid or corrupt kernel image

### ISSUE THREAD

**Issue by cizordj** [mbusb/multibootusb#280]
Host operating system: Linux Deepin 15.5 Desktop

The ISOs that I'm trying to install:

manjaro-deepin-17.1.4-stable-x86_64.iso
link: https://sourceforge.net/projects/manjarolinux-community/files/deepin/17.1.4/

manjaro-budgie-17.0.2-stable-x86_64.iso
link: https://sourceforge.net/projects/manjarolinux-community/files/budgie/17.0.2/

Disk information:
USB contains one primary partition with 7.5 GiB - it's a San Disk Cruzer Blade
file system: Fat32
MultiBoot version: 9.1.0 and 8.8.0 as a super user (I tried with two versions)

Here is the problem:
When I use QEMU to boot directly from ISOs it works well, and when I install them on pen drive it shows
"Invalid or corrupt kernel image"

[multibootusb.log](https://github.com/mbusb/multibootusb/files/1797822/multibootusb.log)

**Comment by mbusb** [comment]
You are running a old version (8.8.0). Try updating to latest version ans if the same issue still persist.

**Comment by cizordj** [comment]
I tested it on both versions, it happens on version 8.8.0 as much as on 9.1.0

2018-03-11 12:51 GMT-03:00 multibootusb <notifications@github.com>:

**Comment by shinji-s** [comment]
It appears to me that they are not prepared for syslinux boot.
Did you try switching to grub (via "Load GRUB2 BootManager") to boot?

**Comment by cizordj** [comment]
No I haven't, do you think that is the problem? If it is, how can I solve it? (anyway I'll try to learn this)

**Comment by shinji-s** [comment]
I used github 'master'  to write manjaro-deepin-17.1.4-stable-x86_64.iso onto my stick and the OS starts up fine via grub. Actually that was my first experience with manjaro and I liked the Look&Feel of the desktop.

> how can I solve it?

Don't you have "Load GRUB2 BootManager" entry in your syslinux boot menu?

**Comment by shinji-s** [comment]
See https://github.com/mbusb/multibootusb/issues/170 for deails.

**Comment by cizordj** [comment]
Hhm I got it, that will surely help me =) Thanks for it, if anything goes wrong I'll let you know
