### ISSUE TITLE
Kali Linux Installer Fails to Detect Installation Medium 

### ISSUE THREAD

**Issue by neilmahaseth** [mbusb/multibootusb#282]
Created a bootable Kali Linux 2018.1 pendrive. The pen drive boots up properly but the kali linux installation fails to detect the installation file. As it expects the file to be present on cdrom. The installation stops at "Detect and Mount step" . The same problem happens with YUMI. The only way to create a bootable kali linux installation usb drive seems by using rufus by using  dd image mode. Or by using custom commands to mount the usb drive as cdrom which is not very convenient. Any alternate method of solving this problem would be greatly appreciated.

**Comment by mbusb** [comment]
It is well known problem for Debian. It is nothing to with multibootusb. The solution lies in the Debian live script/ install script.
