### ISSUE TITLE
Not working with Pentoo

### ISSUE THREAD

**Issue by cvgaviao** [mbusb/multibootusb#288]
I've downloaded pentoo file from here:http://mirror.switch.ch/ftp/mirror/pentoo/Beta/Pentoo_amd64_hardened/pentoo-amd64-hardened-2018.0_RC5.8_pre20180305.iso
I've tested the .iso with virtualbox and worked ok.
Then I've tried to added it to a multibootusb pendrive (with and without existent distributions on it.

So, the files are being copied to pen-drive properly and no error message is shown, but there are no item for it in grub menu while booting with usb.

I noted that in the syslinux.cfg there aren't a BOOT instruction:

>  #start pentoo-amd64-hardened-2018.0_RC5.8_pre20180305
>  LABEL pentoo-amd64-hardened-2018.0_RC5.8_pre20180305
>  MENU LABEL pentoo-amd64-hardened-2018.0_RC5.8_pre20180305
>  #end pentoo-amd64-hardened-2018.0_RC5.8_pre20180305

**Comment by shinji-s** [comment]
Can you try 'devel' branch?
I installed the iso you mentioned on a newly formatted usb drive using that branch and I get the following lines in \syslinux.cfg.

> #start pentoo-amd64-hardened-2018.0_RC5.8_pre20180305
> LABEL pentoo-amd64-hardened-2018.0_RC5.8_pre20180305
> MENU LABEL pentoo-amd64-hardened-2018.0_RC5.8_pre20180305
> BOOT /multibootusb/pentoo-amd64-hardened-2018.0_RC5.8_pre20180305/isolinux/gentoo.bs
> #end pentoo-amd64-hardened-2018.0_RC5.8_pre20180305
> 

By booting under QEMU I see 'pentoo-amd64-hardened-2018.0_RC5.8_pre20180305' in the grub menu and by selecting it I see pentoo boot menu. though memtest86 and HDT fails to load.

**Comment by cvgaviao** [comment]
@shinji-s, I'm going to try now. Thanks...

**Comment by cvgaviao** [comment]
@shinji-s, I tried and didn't work.
this is the content of syslinux.cfg when tried multiboot:
> #start pentoo-amd64-hardened-2018.0_RC6.2
> LABEL pentoo-amd64-hardened-2018.0_RC6.2
> MENU LABEL pentoo-amd64-hardened-2018.0_RC6.2
> #end pentoo-amd64-hardened-2018.0_RC6.2

**Comment by shinji-s** [comment]
Will you post multibootusb.log?

**Comment by cvgaviao** [comment]
@shinji-s, I was not able to find multibootusb.log, perhaps because I run it using `sudo python3 ./multibootusb`, but I copied the log generated at terminal to a file. I'm attaching it...
[multibootusb.log](https://github.com/mbusb/multibootusb/files/1848958/multibootusb.log)

The file ..../multibootusb/pentoo-amd64-hardened-2018.0_RC6.2/iso_file_list.cfg is empty

**Comment by shinji-s** [comment]
> Command '7z l "/home/birdk/Downloads/Linux-ISOs/Pentoo_Linux_amd64_hardened_2018.0_RC6.2/pentoo-amd64-hardened-2018.0_RC6.2.iso" 2> /dev/null' returned non-zero exit status 2.

> The file ..../multibootusb/pentoo-amd64-hardened-2018.0_RC6.2/iso_file_list.cfg is empty

I'm afraid you don't have 7zip installed. 
(Check '/tmp' for the log file.)

> btw, does it lets you select persistence on yours ?

I tried peristence using 'aufs=' boot param but did not succeed.

**Comment by cvgaviao** [comment]
@shinji-s, actually I have 7z installed. I was able to use multiboot with ubuntu and kubuntu already:
 
> multibootusb$ 7z 
7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=pt_BR.UTF-8,Utf16=on,HugeFiles=on,64 bits,4 CPUs Intel(R) Core(TM) i7-4500U CPU @ 1.80GHz (40651),ASM,AES-NI)

I was not able to find the log file.

> I tried persistence using 'aufs=' boot param but did not succeed. Got 'failed to mount aufs on /union' kind of message and then the kernel panicked. Is the kernel mising aufs module compiled in?

pentoo guys from irq told me that now we should use changes or overlayfs=/dev/sdXY

**Comment by shinji-s** [comment]
> actually I have 7z installed. I was able to use multiboot with ubuntu and kubuntu already:

I see. So it must be not having 7zip but 7zip is failing. Will you try the following command and see what happens?
`sudo 7z l "/home/birdk/Downloads/Linux-ISOs/Pentoo_Linux_amd64_hardened_2018.0_RC6.2/pentoo-amd64-hardened-2018.0_RC6.2.iso"
`

> pentoo guys from irq told me that now we should use changes or overlayfs=/dev/sdXY

Thanks for the tip.

**Comment by cvgaviao** [comment]
@shinji-s , seem that the .iso that I was working with is with a problem second 7z. The weird thing is that I've check and some people from pentoo's irq said it is ok... 
anyway going to download one .iso file again...

**Comment by cvgaviao** [comment]
@shinji-s, I've downloaded a new version of pentoo.
When I try to run `7z t Pentoo_Linux_amd64_hardened_2018.0_RC6.3` it returns me a error: `Unexpected end of archive`.

Even so, I was able to use that .iso with the `write image to disk` and then to boot with the usb properly. 

But I was not able to make it to work with multiboot. :(

**Comment by shinji-s** [comment]
@cvgaviao Perhaps you are seeing the same issue as https://github.com/mbusb/multibootusb/issues/308

**Comment by cvgaviao** [comment]
> Perhaps you are seeing the same issue as #308

@shinji-s, certainly it is related to 7zip. 

I tried with 7z in both ubuntu and Win10 and the result was the same, The sad thing is that in no other archive tool I had such problem. I can even mount it and navigate for its folders and files using nautilus :(

**Comment by shinji-s** [comment]
Did you use 7z.exe bundled with mbusb 9.1?
What does it say when you do '7z l {iso-file}'? 
As I wrote previously I can create working stick from _pentoo-amd64-hardened-2018.0_RC5.8_pre20180305.iso_ using 'devel' from github on Windows.

**Comment by shinji-s** [comment]
I can't find iso file for RC6.3. Url?

**Comment by cvgaviao** [comment]
There it is: http://mirror.switch.ch/ftp/mirror/pentoo/Pentoo_amd64_hardened/

**Comment by shinji-s** [comment]
Hmm, I tried RC6.3 and it boots successfully via syslinux and asks me to set root password although boot gets stuck if I kick it from grub. Both cases are under QEMU. I have not tried yet on bare metal.

**Comment by shinji-s** [comment]
Tried on a bare metal. Boots and seems to work fine.

![screenshot_2018-04-06_05-36-18](https://user-images.githubusercontent.com/3322824/38405067-edf67282-39a8-11e8-91fe-06e560b930d1.png)

**Comment by cvgaviao** [comment]
@mbusb ,  excellent news !! :D
I have tried with the version 9.2.0 for windows and I was able to boot with UEFI properly. Well there is some error messages, but it boots and I was able to startx properly.
Had no time to test with Linux though. But, I've opened an issue ticket for 7zip.
[7zip issue](https://sourceforge.net/p/sevenzip/support-requests/251/#)

**Comment by mbusb** [comment]
Thanks for confirming. Closing the issue.
