### ISSUE TITLE
Target USB can't be VFAT?

### ISSUE THREAD

**Issue by seefood** [mbusb/multibootusb#29]
I found that installations failed on a VFAT device, no matter if I had it automounted as my unprivileged user or manually mounted as root. no problems once I reformatted to ext3. Is this a bug or a feature?

**Comment by mbusb** [comment]
multibootusb will install on vfat. Infact, one of the recommended file system is vfat/fat only. I can't reproduce the error and closing as of now. If you find this problem still exist, then open a new one.
