### ISSUE TITLE
CentOS-7-x86_64-DVD-1708.iso not booting

### ISSUE THREAD

**Issue by cwawak** [mbusb/multibootusb#298]
I'm encountering the same issue as #168, with the same dracut-initqueue timeout. This happens both while trying to boot from the multibootusb copied Centos installation files. I notice the same issue when I try to boot the RHEL 7.4 iso (which is similar to Centos) in multibootusb/iso. The Centos ISO is too big to copy to fat32. I can raise a separate issue for RHEL.

I've seen this behavior on multiple systems. A directly "burned" USB key with the same ISO boots fine.

Host Operating system information (Linux/ Windows) and version.
Fedora 27

The ISO your are trying to create and ISO download link.
Centos 7 1708
http://isoredirect.centos.org/centos/7/isos/x86_64/CentOS-7-x86_64-DVD-1708.iso

USB disk information such as partition type, size, file system and so on.
SanDisk SDCZ880-128G-G46 Extreme PRO 128GB USB 3.1 Solid State Flash Drive
```
Disk /dev/sdb: 119.3 GiB, 128043712512 bytes, 250085376 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0x8ff6d7e5

Device Boot Start End Sectors Size Id Type
/dev/sdb1 * 2048 250085375 250083328 119.3G b W95 FAT32
```
Filesystem is FAT32. Fedora Live DVD, Ubuntu Live DVD, Kali all seem to work fine.

MultiBootUSB version you are using.
multibootusb-9.1.0-1.noarch

More importantly, you should provide the log file when raising an issue.
```
=== DEBUG ENABLED ===
Running multibootusb version 9.1.0 from installed system...
Starting multibootusb from Command line...
25008
True
Device /dev/sdb1 is a MBR disk...
Cleaning old multibootusb directory...
Syslinux exist in multibootusb directory...
Executing ==> 7z -ssc- x -y "/mnt/file/infra/iso/CentOS-7-x86_64-DVD-1708.iso" -o/root/.multibootusb/iso_cfg_ext_dir ".cfg" -r 2> /dev/null
Executing ==> 7z -ssc- x -y "/mnt/file/infra/iso/CentOS-7-x86_64-DVD-1708.iso" -o/root/.multibootusb/iso_cfg_ext_dir ".txt" -r 2> /dev/null
Executing ==> 7z -ssc- x -y "/mnt/file/infra/iso/CentOS-7-x86_64-DVD-1708.iso" -o/root/.multibootusb/iso_cfg_ext_dir "isolinux.bin" -r 2> /dev/null
Executing ==> 7z -ssc- x -y "/mnt/file/infra/iso/CentOS-7-x86_64-DVD-1708.iso" -o/root/.multibootusb/iso_cfg_ext_dir ".lst" -r 2> /dev/null
Initiating installation process for CentOS-7-x86_64-DVD-1708
Detected distro type is :centos

Selected ISO is :"CentOS-7-x86_64-DVD-1708.iso"
Selected target device is :"/dev/sdb1"
Please confirm the option.
Y/y/Yes/yes/YES or N/n/No/no/NO
Please enter the option listed above : multibootusb directory already exists. Not copying.
Copying EFI directory to /run/media/cwawak/5599-9433
Installing CentOS-7-x86_64-DVD-1708.iso on /run/media/cwawak/5599-9433/multibootusb/CentOS-7-x86_64-DVD-1708
Executing ==> 7z -ssc- x -y -o"/run/media/cwawak/5599-9433/multibootusb/CentOS-7-x86_64-DVD-1708" "/mnt/file/infra/iso/CentOS-7-x86_64-DVD-1708.iso" 2> /dev/null
ISO extracted successfully. Sync is in progress...

Found syslinux version 4

Executing ==> /root/.multibootusb/syslinux/bin/syslinux4 -i -d "/multibootusb/CentOS-7-x86_64-DVD-1708/isolinux" /dev/sdb1

Syslinux install on distro directory is successful...

Executing ==> dd if=/dev/sdb1 of="/run/media/cwawak/5599-9433/multibootusb/CentOS-7-x86_64-DVD-1708/isolinux/centos.bs" count=1

Bootsector copy is successful...

Using mbr.bin msdos mbr install.

Executing ==> /root/.multibootusb/syslinux/bin/syslinux4 -i -d multibootusb /dev/sdb1

Default syslinux install is success...

Executing ==> dd bs=440 count=1 conv=notrunc if=/usr/share/multibootusb/data/tools/mbr.bin of=/dev/sdb

mbr install is success...

Checking boot flag on /dev/sdb

Disk /dev/sdb already has boot flag.

Replacing efi binary with msdos compatible one...
[Errno 2] No such file or directory: '/run/media/cwawak/5599-9433/EFI/BOOT/bootx64-msdos.efi'
Failed to replace efi binary...
Replacing core.img with msdos compatible one...
[Errno 2] No such file or directory: '/run/media/cwawak/5599-9433/multibootusb/grub/core-msdos.img'
Failed to replace core.img binary...
Updating distro specific config files...
Updating multibootusb config file...
Trying to create loopback.cfg
loopback.cfg file is set to /run/media/cwawak/5599-9433/multibootusb/CentOS-7-x86_64-DVD-1708/loopback.cfg
loopback.cfg file is successfully created.
You must send this file for debugging if something goes wrong.
Found EFI/BOOT/grub.cfg
Updating grub.cfg file...
size of the ISO is 4.2G
Updated entry in grub.cfg...
Updated entry in syslinux.cfg...
multibootusb EFI image already exist. Not copying...
Finished installing CentOS-7-x86_64-DVD-1708

```
Any other information, not listed above, you feel will help me in figure out your issue.

**Comment by cwawak** [comment]
It turns out RHEL and Centos aren't finding the stage2 image.

I tried to apply the UUID=5599-9433 from the USB drive to RHEL like so:

```
menuentry 'Install Red Hat Enterprise Linux 7.4' --class fedora
--class gnu-linux --class gnu --class os {
linux /multibootusb/rhel-server-7.4-x86_64-dvd/images/pxeboot/vmlinuz
inst.stage2=hd:LABEL=RHEL-7.4\x20Server.x86_64 quiet
initrd /multibootusb/rhel-server-7.4-x86_64-dvd/images/pxeboot/initrd.img
}
```
(to this)
```
menuentry 'Install Red Hat Enterprise Linux 7.4' --class fedora
--class gnu-linux --class gnu --class os {
linux /multibootusb/rhel-server-7.4-x86_64-dvd/images/pxeboot/vmlinuz
inst.stage2=hd:LABEL=UUID=5599-9433:/multibootusb/rhel-server-7.4-x86_64-dvd
debug
initrd /multibootusb/rhel-server-7.4-x86_64-dvd/images/pxeboot/initrd.img
}
```

That worked to get things booted! The installer now complains about not being able to find the repository, but I think I'm close to getting that fixed as well.

How can we get the UUID issue fixed in the USB creator?

**Comment by shinji-s** [comment]
> That worked to get things booted! 

Good catch.
I think the place to put the fix is update_distro_cfg_files() function in scripts/update_cfg_file.py.
Before fixing the function, it may be good idea to first tweak distro() function in scripts/distro.py so that mbusb recognize centos-install rather than falling back to generic memdisk-iso.
With that said, you may want to wait a little before working on update_cfg_file.py as  I'm now working on the same file to introduce infrastructure to do the parameter rewrite.

**Comment by shinji-s** [comment]
Hmm, code to detect 'centos' is in place. Why does not it tigger?

**Comment by cwawak** [comment]
Thanks @shinji-s! Really appreciate everyone's work on this project.

I'm kinda mixing RHEL and Centos here - they should behave the same, but naming is different, so I should probably open a new issue for RHEL. I'll do that.

**Comment by shinji-s** [comment]
@cwawak 
Thanks to your finding, now I  get CentOS-7-x86_64-(DVD|Minmal|NetInstall)-1708.iso booting successfully. You can specify repository location with 'inst.repo=' boot param. A bad news is that you can't specify expanded file tree on usb stick using 'repo=hd:UUDI={uuid}:{path}' as {path} needs to point to an iso file.

**Comment by amosbird** [comment]
Hello, I've tried installing `CentOS-7-x86_64-Minimal-1804.iso` and stumbled into this error `failed to set new efi boot target` . Is that somehow related to multibootusb?

**Comment by haxj** [comment]
Hello, I've been able to install CentOS along with other OSes. The thing is, multibootusb seems to support just FAT32, but FAT32 can't handle files with size larger than 4 GB, e.g. CentOS ISO file. I ended up with a 4 GB corrupted ISO file in that FAT32 partition, which is why CentOS installer complain about the mising repo.

So I create another partition on the USB (ext2/3/4, not NTFS because CentOS by default cannot handle it), copy CentOS ISO to it, use multibootusb to install CentOS on the other FAT32 partition. To instruct CentOS to use that ISO file, point inst.repo parameter in the following files to the ISO location:
/multibootusb/CentOS-7-x86_64-DVD-1810/isolinux/isolinux.cfg
/multibootusb/CentOS-7-x86_64-DVD-1810/isolinux/syslinux.cfg
/multibootusb/CentOS-7-x86_64-DVD-1810/EFI/BOOT/grub.cfg
E.g. inst.repo=hd:UUID=cbd870d2-96f5-4d53-bfc6-5c11e8144b35:/CentOS-7-x86_64-DVD-1810.iso
You can remove the corrupted iso file in /multibootusb/centos directory

I hope this issue can be resolved in some future releases.

**Comment by cwawak** [comment]
This is an old, old issue. I'm closing it.
