### ISSUE TITLE
Knoppix won't boot

### ISSUE THREAD

**Issue by seefood** [mbusb/multibootusb#30]
downloaded 7.4.2 (latest Knoppix), installed fine, but does not boot. and thuis raises a question - I have no way of finding out if it should have worked. where's the list of supported distros? can't find one here on Github nor on the official site...

**Comment by mbusb** [comment]
Knoppix will boot now properly. Pushed the patch just now.

> where's the list of supported distros? 

It is very difficult to tell which are the distros are supported. multibootusb uses generic way to detect and install distros. If multibootusb say that distros is not supported then you can file an issue here. I will try to add it in the next release.
