### ISSUE TITLE
Add support for AntiX Linux

### ISSUE THREAD

**Issue by Philippe734** [mbusb/multibootusb#301]
Please, add support for AntiX Linux 32 bits, useful distro for very slow and old computers. Currently, the version 16.3 and 17.1 are not supported in multibootusb 9.1. After distro installed on the usb device, AntiX is not able to boot, see the screenshot:
![image](https://user-images.githubusercontent.com/24923693/38030930-4cbbc7b0-329a-11e8-8548-776bd8bd9ee2.png)
![image](https://user-images.githubusercontent.com/24923693/38031110-c7579008-329a-11e8-9654-b980b96fe4b2.png)
Official site for AntiX: https://antixlinux.com/

**Comment by mbusb** [comment]
Tested the latest Antix release with version 9.2.0. It works. If not, please report as a new issue.

**Comment by Philippe734** [comment]
Very fast fixed, thanks ! I confirm, AntiX 17.1 32bits works fine with Multibootusb 9.2.0.

**Comment by tosim91** [comment]
My MultiBoot v is 9.2.0, but antiX v17.4,32b,full will NOT boot.
