### ISSUE TITLE
Slackware packaging is also available

### ISSUE THREAD

**Issue by metemaddar** [mbusb/multibootusb#32]
Hi,
Slackware's official packaging is also available;
Here it is:
http://slackbuilds.org/repository/14.1/system/multibootusb/

Cheers

**Comment by mbusb** [comment]
Thank you very much for the build.

**Comment by mbusb** [comment]
You may want to update the build to latest release 8.6.0.

**Comment by metemaddar** [comment]
Thanks a lot.
Of course it needs a small change( #167 ) in order to start well on Slakware with PyQt4.
