### ISSUE TITLE
UEFI Support

### ISSUE THREAD

**Issue by ajerijian** [mbusb/multibootusb#35]
With more and more newer computer systems using UEFI for boot, it would be great if this tool offered the ability to create multiboot USB drives that can be booted on UEFI systems (perhaps not necessarily with SecureBoot enabled).

This may be a wish-list item.

**Comment by mbusb** [comment]
UEFI is already supported via 'ISO Imager'. But remember that this process is destructive and delete all files in the USB. 

Untill syslinux adds full support for UEFI, multibootusb will support UEFI only through 'ISO Imager'.

**Comment by go2null** [comment]
Apparently, Syslinux [does](http://www.syslinux.org/wiki/index.php?title=Install#UEFI) have [some](https://wiki.archlinux.org/index.php/syslinux#UEFI_Systems) UEFI  support.
