### ISSUE TITLE
Error generating rpm into suse's build service

### ISSUE THREAD

**Issue by malkavi** [mbusb/multibootusb#365]
After this commit #363, I can't build multibootusb using opensuse build service to generate a package. 
"python setup.py build" use the log path "/var/.." hardcoded and the build service can't write in that folder. Can be modified somehow for the "build" and "install" only?

My suse repo:
https://build.opensuse.org/package/show/home:malkavi/multibootusb-devel

**Comment by shinji-s** [comment]
Thank you for reporting this issue. Will you please see if https://github.com/mbusb/multibootusb/pull/366 fixes the problem?

**Comment by malkavi** [comment]
Thanks! I have test it and it's compiling correctly.
