### ISSUE TITLE
Partitioning logic

### ISSUE THREAD

**Issue by colemickens** [mbusb/multibootusb#377]
How does this tool handle partitioning? If I remove ISOs from the middle, do I get holes? Are the holes filled when possible? Does it always try to write to the front-most available free space? Can it be instructed to make sure it never touches certain parts of the disk?

**Comment by shinji-s** [comment]
In the basic operation mode, mbusb does not at all deal with partitioning or free space management. It extracts files out of the specified iso and writes them onto the target filesystem or delete them from the target filesystem.
Free space management is taken care of by the underlining filesystem driver.

**Comment by mbusb** [comment]
This tool will only use the existing partition under normal mode (extraction mode). If you are using imager functionality, then all partitioning schemes will be destroyed due to use of `dd`
