### ISSUE TITLE
USB flash drive is not in list

### ISSUE THREAD

**Issue by Yanpas** [mbusb/multibootusb#38]
I have several usb sticks and one is not displayed in the forst tab of this app (multiboot).
Details:
```
Bus 004 Device 013: ID 1307:0165 Transcend Information, Inc. 2GB/4GB Flash Drive

```

**Comment by mbusb** [comment]
Do you still have this issue?

**Comment by Yanpas** [comment]
@mbusb yes. Noticable that this flash drive is detected in system as /dev/sdd (it doesn't have /dev/sdd1 , /dev/sdd2 ... partitions). Maybe you will add tick to list all drives in the system?

**Comment by mbusb** [comment]
Did you try with the latest source? Can you post the error log (terminal output) or screenshot?

**Comment by Yanpas** [comment]
![_2016-05-16_17-58-49](https://cloud.githubusercontent.com/assets/7345761/15293262/dd6c7436-1b8f-11e6-9d7c-5ad006009627.png)

**Comment by Yanpas** [comment]
But it is succesfully detected here! 
![_2016-05-16_18-00-17](https://cloud.githubusercontent.com/assets/7345761/15293312/15a4adc8-1b90-11e6-8718-8541c3cf042d.png)

**Comment by mbusb** [comment]
Hahaha. This is not a bug.

It is supposed to do that. For installing distro on usb (by way of extracting from iso files), there should be a partition on a target USB disk. But for installing distro using 'ISO Imager' feature (or you can call it as 'dd' method), the ISO file is directly written on the disk and not on the partition. Therefore, it is not a bug in multibootusb. Just add partition to your USB disk and it should work on both way.

**Comment by Yanpas** [comment]
Ah, got it! :) Created partition table in gparted and now it is recognized. Didn't know that I can use flash drive without MBR
