### ISSUE TITLE
Unable to install Linux Mint

### ISSUE THREAD

**Issue by Yanpas** [mbusb/multibootusb#40]
Using multibootusb flash drive makes installing process to fail. Burning ISO doesn't cause any errors. No matterif persistent file was created or not
![screenshot_2016-01-24_14-17-00](https://cloud.githubusercontent.com/assets/7345761/12535958/84d0472c-c2a6-11e5-9638-c7e7e0986ab0.png)

**Comment by LibertatisPrius** [comment]
I have also run into this issue. I suspect the persistence feature is to blame and am reinstalling LinuxMint now to test my theory. (I am using LinuxMint 17.3 Cinnamon 64bit.)

**Comment by Yanpas** [comment]
I have tried both (with persistance and without) - the outcome is the same: error.

**Comment by mbusb** [comment]
The purpose of the software is to make live usb. If you cant install the OS after making live usb then I really don't have any solution. It is beyond the scope of this project.
