### ISSUE TITLE
Crash - OSError in disk_usage

### ISSUE THREAD

**Issue by raphaelh** [mbusb/multibootusb#42]
I'm using multibootusb 7.5.0-1 package in XUbuntu 15.04

When I try to add "xubuntu-14.04.3-desktop-i386.iso", it crashes:
```
ISO passed.
Distro detected is ubuntu
Persistence option is available.
Persistence choosen is 512 MB
Traceback (most recent call last):
  File "/usr/bin/multibootusb", line 70, in <lambda>
    str(self.ui.lineEdit.text()).strip()))
  File "/usr/bin/multibootusb", line 269, in onCreateClick
    if config.install_size >= self.usb.disk_usage(self.usb.get_usb(usb_disk).mount).free:
  File "/usr/lib/python2.7/dist-packages/scripts/usb.py", line 55, in disk_usage
    st = os.statvfs(mount_path)
OSError: [Errno 2] Aucun fichier ou dossier de ce type: 'Not mounted.'
```

I can do specific tests if you want!

**Comment by mbusb** [comment]
You must mount the disk and use multibootusb.

**Comment by raphaelh** [comment]
Perhaps you could display a message telling that instead of crashing? Isn't it possible to mount it when it's not already mounted?

**Comment by mbusb** [comment]
Commit https://github.com/mbusb/multibootusb/commit/432f010e94dc3752de714247e5b56c922479d10b should fix the problem.
