### ISSUE TITLE
Could not find resource 'data/multibootusb/grub/menus.zip'.

### ISSUE THREAD

**Issue by chlorophyll-zz** [mbusb/multibootusb#431]
no more text

**Comment by chlorophyll-zz** [comment]
Resolved, the Problem lies in the Archlinux AUR script. Closed.

**Comment by ckotte** [comment]
@chlorophyll-zz How did you resolve this? I also have the issue with the git repo..

**Comment by mathieu-aubin** [comment]
@chlorophyll-zz Altho this doesnt affect me, it makes sense that when you solve something, you SHARE your steps. It's only fair to give back to the community and the internet in general. Think of Github as an archive of answers, as much as you use stackoverflow, it can be used by many people to solve their issues.

**Comment by chlorophyll-zz** [comment]
i have much so resolved this, in that way, that i found the github repo not the reason for the error but the aur script. the repo packs the application in a deb archive, where the issue doesnt exists. the issue exists because of the difference in packaging the application for debian and arch linux. you have to contact the author of the arch linux aur script. besides contacting the author here, you could write a universal packaging method yourself instead of rambling with me here off-topic without sense.

**Comment by chlorophyll-zz** [comment]
@mbusb the difference in the packaging method for arch linux and debian is a problem, because the arch linux users are getting pushed to this issue because of the unfixed arch linux user script that packages the application in a different way.

**Comment by mathieu-aubin** [comment]
Why would you delete/edit your initial post? Care to elaborate on that? Makes no sense to me, really

**Comment by chlorophyll-zz** [comment]
@mathieu-aubin  issue is not in master

**Comment by chlorophyll-zz** [comment]
@ckotte @mathieu-aubin it also makes no sense that you would ask me to resolve an issue only the maintainer could fix. issue is in aur repo. issues does not originate from repo. btw this is a proxy conversation that the repo maintainer and the aur maintainer should have.

**Comment by ckotte** [comment]
@chlorophyll-zz No one asked you to resolve any AUR package issue!? I just asked how you fixed this particular issue. 
I have this issue with the git repo. No AUR involved. I can boot some of the ISOs. Looks like it's not that important. The aur version by the way doesn't even work. 

Anyway, I'm out of here since you deleted your original text and a proper conversation isn't possible with you. Little baby.

**Comment by chlorophyll-zz** [comment]
@ckotte listen up:
Cyberbullying or cyberharassment is a form of bullying or harassment using electronic means. Cyberbullying and cyberharassment are also known as online bullying. It has become increasingly common, especially among teenagers.[1] Cyberbullying is when someone, typically teens, bully or harass others on the internet, particularly on social media sites. Harmful bullying behavior can include posting rumors, threats, sexual remarks, a victims' personal information, or pejorative labels (i.e. hate speech).[2] Bullying or harassment can be identified by repeated behavior and an intent to harm.[3] Victims may experience lower self-esteem, increased suicidal ideation, and a variety of negative emotional responses, including being scared, frustrated, angry, and depressed.[4]

Awareness in the United States has risen in the 2010s, due in part to high-profile cases.[5][6] Several US states and other countries have laws specific to cyberbullying.[7] Some are designed to specifically target teen cyberbullying, while others use laws extending from the scope of physical harassment.[8] In cases of adult cyberharassment, these reports are usually filed beginning with local police.[9]

Research has demonstrated a number of serious consequences of cyberbullying victimization.[10]

Internet trolling is a common form of bullying over the Internet in an online community (such as in online gaming or social media) in order to elicit a reaction, disruption, or for someone's own personal amusement.[11][12] Cyberstalking is another form of bullying or harassment that uses electronic communications to stalk a victim; this may pose a credible threat to the victim.[13]

Not all negative interaction online or on social media can be attributed to cyberbullying. Research suggests that there are also interactions online that result in peer pressure, which can have a negative, positive, or neutral impact on those involved.[14][15][16]

**Comment by ckotte** [comment]
lol

**Comment by chlorophyll-zz** [comment]
yeah, whatever you say.

**Comment by chlorophyll-zz** [comment]
@mbusb dupe of #480 #466 #435 #425

**Comment by chlorophyll-zz** [comment]
For reference: these issues all resemeble the following error:

> Could not find resource 'data/multibootusb/grub/menus.zip'.
> Unable to extract menu files to USB disk.

**Comment by chlorophyll-zz** [comment]
like you said. last of laughs

**Comment by Soundtoxin** [comment]
Is there a workaround for this in the meantime? Where do I get menus.zip and where do I place it? It mentions a relative path, but I got this from the NixOS repos, so it's unclear where the data folder is.

**Comment by bartman081523** [comment]
the "fork" (solely added menus.zip from menus folder items) is merged. thanks to the maintainer.

**Comment by Soundtoxin** [comment]
> could you try my "fork"?

When using your fork I get the NameError that seems to be common. I seem to get the same thing using the source for the main version. Somehow the packaged version was different.
```
brad@anpan:~/ > sudo python3 /home/brad/Downloads/multibootusb/multibootusb -c -i /home/brad/Downloads/nixos-graphical-19.09.1320.4ad6f1404a8-x86_64-linux.iso,/home/brad/Downloads/guix-system-install-1.0.1.x86_64-linux.iso,/home/brad/Downloads/void-live-x86_64-20181111-enlightenment.iso,/home/brad/Downloads/helium-5-amd64.hybrid.iso,/home/brad/Downloads/artix-lxqt-runit-20181008-x86_64.iso,/home/brad/Downloads/ubuntu-19.10-desktop-amd64.iso,/home/brad/Downloads/TinyCore-current.iso,/home/brad/Downloads/CorePlus-current.iso -t /dev/sdc1
Using python version  3.7.5 (default, Oct 14 2019, 23:08:55) 
[GCC 8.3.0] on platform Linux-4.19.86-x86_64-with-glibc2.2.5
Traceback (most recent call last):
  File "/home/brad/Downloads/multibootusb/multibootusb", line 163, in <module>
    config.image_path = arg.split(',')
NameError: name 'config' is not defined
```

**Comment by bartman081523** [comment]
@Soundtoxin 
in the root dir multibootusb try witth

> python3 setup.py build

then your multibootusb command

> sudo python3 multibootusb -c -i /home/brad/Downloads/nixos-graphical-19.09.1320.4ad6f1404a8-x86_64-linux.iso,/home/brad/Downloads/guix-system-install-1.0.1.x86_64-linux.iso,/home/brad/Downloads/void-live-x86_64-20181111-enlightenment.iso,/home/brad/Downloads/helium-5-amd64.hybrid.iso,/home/brad/Downloads/artix-lxqt-runit-20181008-x86_64.iso,/home/brad/Downloads/ubuntu-19.10-desktop-amd64.iso,/home/brad/Downloads/TinyCore-current.iso,/home/brad/Downloads/CorePlus-current.iso -t /dev/sdc1

**Comment by Soundtoxin** [comment]
@chlorophyll-zz 
> `python3 setup.py build`

I get a warning near the start, and then when trying my command again it seems to fail with the same error again.

```
brad@anpan:~/Downloads/multibootusb/ > python3 setup.py build
/nix/store/drr8qcgiccfc5by09r5zc30flgwh1mbx-python3-3.7.5/lib/python3.7/distutils/dist.py:274: UserWarning: Unknown distribution option: 'include_package_data'
  warnings.warn(msg)
running build
running build_py
copying scripts/syslinux.py -> build/lib/scripts
copying scripts/qemu.py -> build/lib/scripts
copying scripts/persistence.py -> build/lib/scripts
copying scripts/imager.py -> build/lib/scripts
copying scripts/mbusb_cli.py -> build/lib/scripts
copying scripts/admin.py -> build/lib/scripts
copying scripts/uninstall_distro.py -> build/lib/scripts
copying scripts/param_rewrite.py -> build/lib/scripts
copying scripts/mbusb_gui.py -> build/lib/scripts
copying scripts/debug.py -> build/lib/scripts
copying scripts/menus.py -> build/lib/scripts
copying scripts/win32.py -> build/lib/scripts
copying scripts/update_cfg_file.py -> build/lib/scripts
copying scripts/isodump3.py -> build/lib/scripts
copying scripts/gen.py -> build/lib/scripts
copying scripts/__init__.py -> build/lib/scripts
copying scripts/distro.py -> build/lib/scripts
copying scripts/grub.py -> build/lib/scripts
copying scripts/install.py -> build/lib/scripts
copying scripts/config.py -> build/lib/scripts
copying scripts/usb.py -> build/lib/scripts
copying scripts/iso.py -> build/lib/scripts
copying scripts/_7zip.py -> build/lib/scripts
copying scripts/osdriver.py -> build/lib/scripts
copying scripts/udisks.py -> build/lib/scripts
copying scripts/pyudev/glib.py -> build/lib/scripts/pyudev
copying scripts/pyudev/monitor.py -> build/lib/scripts/pyudev
copying scripts/pyudev/pyqt4.py -> build/lib/scripts/pyudev
copying scripts/pyudev/_errors.py -> build/lib/scripts/pyudev
copying scripts/pyudev/wx.py -> build/lib/scripts/pyudev
copying scripts/pyudev/pyqt5.py -> build/lib/scripts/pyudev
copying scripts/pyudev/version.py -> build/lib/scripts/pyudev
copying scripts/pyudev/_qt_base.py -> build/lib/scripts/pyudev
copying scripts/pyudev/discover.py -> build/lib/scripts/pyudev
copying scripts/pyudev/__init__.py -> build/lib/scripts/pyudev
copying scripts/pyudev/_util.py -> build/lib/scripts/pyudev
copying scripts/pyudev/core.py -> build/lib/scripts/pyudev
copying scripts/pyudev/_compat.py -> build/lib/scripts/pyudev
copying scripts/pyudev/pyside.py -> build/lib/scripts/pyudev
copying scripts/pyudev/device/_device.py -> build/lib/scripts/pyudev/device
copying scripts/pyudev/device/__init__.py -> build/lib/scripts/pyudev/device
copying scripts/pyudev/_ctypeslib/utils.py -> build/lib/scripts/pyudev/_ctypeslib
copying scripts/pyudev/_ctypeslib/_errorcheckers.py -> build/lib/scripts/pyudev/_ctypeslib
copying scripts/pyudev/_ctypeslib/__init__.py -> build/lib/scripts/pyudev/_ctypeslib
copying scripts/pyudev/_ctypeslib/libudev.py -> build/lib/scripts/pyudev/_ctypeslib
copying scripts/pyudev/_ctypeslib/libc.py -> build/lib/scripts/pyudev/_ctypeslib
copying scripts/pyudev/_os/pipe.py -> build/lib/scripts/pyudev/_os
copying scripts/pyudev/_os/poll.py -> build/lib/scripts/pyudev/_os
copying scripts/pyudev/_os/__init__.py -> build/lib/scripts/pyudev/_os
copying scripts/gui/ui_multibootusb.py -> build/lib/scripts/gui
copying scripts/gui/resources.py -> build/lib/scripts/gui
copying scripts/gui/__init__.py -> build/lib/scripts/gui
copying scripts/gui/ui_about.py -> build/lib/scripts/gui
copying scripts/progressbar/progressbar.py -> build/lib/scripts/progressbar
copying scripts/progressbar/widgets.py -> build/lib/scripts/progressbar
copying scripts/progressbar/__init__.py -> build/lib/scripts/progressbar
copying scripts/progressbar/compat.py -> build/lib/scripts/progressbar
running build_scripts
copying and adjusting multibootusb -> build/scripts-3.7

brad@anpan:~/Downloads/multibootusb/ > sudo python3 /home/brad/Downloads/multibootusb/multibootusb -c -i /home/brad/Downloads/nixos-graphical-19.09.1320.4ad6f1404a8-x86_64-linux.iso,/home/brad/Downloads/guix-system-install-1.0.1.x86_64-linux.iso,/home/brad/Downloads/void-live-x86_64-20181111-enlightenment.iso,/home/brad/Downloads/helium-5-amd64.hybrid.iso,/home/brad/Downloads/artix-lxqt-runit-20181008-x86_64.iso,/home/brad/Downloads/ubuntu-19.10-desktop-amd64.iso,/home/brad/Downloads/TinyCore-current.iso,/home/brad/Downloads/CorePlus-current.iso -t /dev/sdc1
Using python version  3.7.5 (default, Oct 14 2019, 23:08:55)
[GCC 8.3.0] on platform Linux-4.19.86-x86_64-with-glibc2.2.5
Traceback (most recent call last):
  File "/home/brad/Downloads/multibootusb/multibootusb", line 163, in <module>
    config.image_path = arg.split(',')
NameError: name 'config' is not defined
```

**Comment by chlorophyll-zz** [comment]
try with 1 Iso file first, see if the error remains
