### ISSUE TITLE
http://multibootusb.org/ has broken link to Open Source icon

### ISSUE THREAD

**Issue by milankni** [mbusb/multibootusb#46]
The href is correct, the img src is wrong:
`<div id="text-3" class="widget-wrapper widget_text">`
`<div id="widget-title-one" class="widget-title-home">`
`<h3>Open Source</h3>`
`</div>`
`<div class="textwidget"><p style="text-align: justify;">`
`<a href=http://multibootusb.org/wp-content/uploads/2015/02/open-source-48-48.png>`
`<img class="alignleft size-full wp-image-22" alt="open-source-48-48" src="http://multibootusb.org/wp-content/uploads/2013/12/open-source-48-48.png" width="48" height="48" /></a>`
`MultiBootUSB is released under GPL. It uses best of Open Source software in the web.</p></div>`

**Comment by mbusb** [comment]
Solved.
