### ISSUE TITLE
Error While Installing Syslinux

### ISSUE THREAD

**Issue by alexmulligan** [mbusb/multibootusb#463]
When the program tries to install syslinux, it hangs indefinitely.  It will say "Installing Syslinux" and sit at 0% until you close the program.  This happens when it tries to install syslinux after installing an ISO, and it also happens when you try to just install syslinux separately in the Install Syslinux tab.

I launched the gui program from a terminal to get the output, and I got this error:

```
Installing default syslinux on /dev/sdb1
Using gptmbr.bin for mbr install.
Could not find resource 'data/tools/gptmbr.bin'.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/scripts/mbusb_gui.py", line 387, in onInstall_syslinuxClick
    ret = syslinux_default(config.usb_disk)
  File "/usr/lib/python3/dist-packages/scripts/syslinux.py", line 107, in syslinux_default
    mbr_install_cmd = 'dd bs=440 count=1 conv=notrunc if=' + mbr_bin + ' of=' + usb_disk[:-1]
TypeError: must be str, not NoneType
```

_MultiBootUSB 9.2.0_
_Ubuntu 18.04.2_

**Comment by alexmulligan** [comment]
After looking in the source files, I found that as a workaround I can use a USB Drive with a MSDOS partition table instead of a GPT one.  The file "gtpmbr.bin" is missing but the other "mbr.bin" is not.  This workaround is working, but I would still like to use GPT.  Where would I be able to find the "gptmbr.bin" that it needs and where should I put the file (it says it's looking for `data/tools/gptmbr.bin`, but I cannot find where it should be)?

**Comment by mathieu-aubin** [comment]
why would you need/want/require gpt partition?

from what i understand, this isnt meant for long runs or anything "permanent".

Every *nix distrib can read/use a msdos part without much problems -- if any.

gpt, on the other hand, will most certainly create usability issues for systems like, say, older windows versions and such....

Not all hardware or OS support the GPT system  and that being said , having it as a requirement goes against the purpose of having a cross-platform/device/system usb key that you can use on everything for that ultimate repair you simply wouldnt have been able to perform

maybe my opinion makes no sense tho, if so... please educate me ;)

**Comment by alexmulligan** [comment]
I did not realize that there is no disadvantage to use msdos partition tables.  Is there any specific advantage to using GPT in general or for any specific use?

**Comment by mathieu-aubin** [comment]
checkout https://www.petri.com/gpt-vs-mbr-based-disks

**Comment by alexmulligan** [comment]
Yes the installation was successful with MBR.
