### ISSUE TITLE
Uninstalling multibootusb

### ISSUE THREAD

**Issue by bushyiv** [mbusb/multibootusb#464]
Multiboot was installed on Linux Mint 19.  I created a multiboot usb flash drive with several iso.  Everything worked well but I need to re-purpose the usb drive and cannot find how it can be done.  I have also have a win10 box if it can be done easier on it rather than the Linux box.

**Comment by mathieu-aubin** [comment]
format the drive to whatever filesystem you need to reuse it

**Comment by bushyiv** [comment]
Your suggestion is not possible.  I have spent several days on many forums and everything I have tried fails.  The flash drive looks like a CDROM to the file system, so gparted, dd, disks, hdparm -r0, I tried mounting the flash drive with the switch to make it RW and that failed as well.sudo mount -t vfat -o rw /dev/sdc1 /media/USBdrive
mount: /media/USBdrive: WARNING: device write-protected, mounted read-only.
Everything fails returning an error that the device is READ ONLY!

**Comment by Akito13** [comment]
@mathieu-aubin The problem is that this flash drive worked perfectly fine, before multibootusb was used upon it. Now it is rendered useless, because it is somehow turned read-write in every single situation. It is neither possible to change the permissions, remount it with RW permissions, format it, delete it nor anything of that type. The only way to operate with the USB drive is by using this software. Nothing else works. How is that?

**Comment by bushyiv** [comment]
@Akito13:  Correction to your statement: "Now it is rendered useless, because it is somehow turned read-write in every single situation" It should say it is READ ONLY.

**Comment by mathieu-aubin** [comment]
i will check more in depth but... i dont know what happenned for you since i can delete everything amd format whichever drive i use with multibootusb.

**Comment by mathieu-aubin** [comment]
Okay, unless you provide more details (or even a video, screenshots...) i won't be able to help.

I've tried to replicate your problem with 5 different usb keys and i have always been able to format them after installing whatever stuff on them, from multiboousb.

I don't want to insult you but... are you unmounting the drive before trying to mess with the partitions?

**Comment by Akito13** [comment]
@mathieu-aubin 

> On Linux:
> gparted
> disks
> hdparm -r0
> fdisk
> dban
> 
> On WIN10:
> HDDLLF.4.40.exe

Some of these programs either do not mount the drive in the first place (dban), would warn you very obviously you need to unmount your drive (disks, gParted) and others work entirely differently (HDDLLF.4.40.exe). It's really not like he just popped onto Github, because he had a problem with this flash drive for 2 minutes and then gave up working on it. Opening an issue here was a desparate last resort type of choice, since nothing else works, at all.

**Comment by Akito13** [comment]
@bushyiv 
Post the link to your flash drive model and provide a video or an [asciinema](https://asciinema.org/) to show what happens.

**Comment by bushyiv** [comment]
Discovered that there is a Sandisk controller bug that causes this problem, it has nothing to do with any software installed on it by an end user.  Sandisk acknowledges the problem w/o any solution. I will be making a warranty claim, it's only one year old, warranty period is for five years.

**Comment by Akito13** [comment]
@mathieu-aubin You should exclude this specific device from the list of compatible devices. Perhaps with a warning disclaimer.

@bushyiv Can you post the exact model number of your product? So it will be easier to do the above.

**Comment by bushyiv** [comment]
SanDisk Ultra Fit USB 3.1 Flash Drive

**Comment by Akito13** [comment]
@bushyiv I would advise the same as @mathieu-aubin said.

**Comment by bushyiv** [comment]
I could not find again the link that talked about the Sandisk Flash drive issue.  So, I called Sandisk to discuss the issue with their tech support, their support new exactly the problem, it's called a "Write Protection Error".  There is no solution,fortunately a sandisk flash drive has a 5 year warranty, they readily give you a RMA to return it for a replacement which I already did..

**Comment by bushyiv** [comment]
Of course after I close this thread I finally find the link I was after: 
https://askubuntu.com/questions/409520/unable-to-open-dev-sdb-read-write-read-only-file-system
Here's the relevant part of the posted thread: 
 from the Sandisk forum:

    This is an offical answer if you contact customer service:

    "I understand that you are getting write protection error while accessing your Cruzer flash drive. The flash drive has detected a potential fault and has become write protected to prevent data loss. There is no method to fix this. You will need to backup your data and replace the flash drive. Our team of developers is in combination with the OS developers looking into a solution to resolve this issue. Please note that only a minor percentage of users are experiencing the write protection issue and these are the customers posting on the internet to find a solution."

So likely there is no way to solve it.

**Comment by mathieu-aubin** [comment]
> I could not find again the link that talked about the Sandisk Flash drive issue. So, I called Sandisk to discuss the issue with their tech support, their support new exactly the problem, it's called a "Write Protection Error". There is no solution,fortunately a sandisk flash drive has a 5 year warranty, they readily give you a RMA to return it for a replacement which I already did..

Did you need to pay for shipping in and out? Any other types of spendage you had to do to get a replacement?

**Comment by bushyiv** [comment]
Did not have to pay for shipping, no expenses incurred.

**Comment by mh166** [comment]
If only I had known... came across the very same problem many times before with different types and sizes of SanDisk flash drives. Only that I instantly attributed it to being a bad drive (as it was writeable neither on Windows nor Linux, whereas the latter is always a bad sign 😉) and it might "just happen" from time to time. Wish I would've got them replaced. 🙄

@Akito13, @mathieu-aubin I guess, therefore, it's rather not as easy as putting up a list of specific models – a variety of them might use the same controller while some of the same models could even use different controllers. And, as stated by the support, it might only concern a small percentage of the users...

But thanks for sharing your findings with us, @bushyiv 👍
