### ISSUE TITLE
64-bit syslinux6 produces an incompatible ldlinux.c32

### ISSUE THREAD

**Issue by yurikhan** [mbusb/multibootusb#49]
Versions:
- Host system: Ubuntu 16.04 amd64
- Distribution-provided `syslinux` package: installed, version 3:6.08+dfsg-11ubuntu1
- multibootusb: 7.5.0 installed from deb; also tested on master
- image: [clonezilla-2.4.6-25-i686.iso](https://osdn.jp/frs/redir.php?m=cznic&f=%2Fclonezilla%2F65892%2Fclonezilla-live-2.4.6-25-i686.iso)

To reproduce:
1. Format a USB drive.
2. Use multibootusb to add CloneZilla to the drive. Notice that the installation log does not mention copying syslinux modules.
3. Boot.
4. Select CloneZilla in the top boot menu.

Expected behavior: the CloneZilla boot menu appears.

Observed behavior: the following three lines are repeated indefinitely.

```
Undef symbol FAIL: __syslinux_debug_enabled
Failed to load libcom32.c32
Failed to load COM32 file vesamenu.c32
```

Additional considerations:
- During installation, `syslinux6` (bundled with multibootusb in the `/usr/multibootusb/tools/syslinux/syslinux_linux_64.zip` archive) is invoked, with `/multibootusb/clonezilla-live-2.4.6-25-i686/syslinux` as the target directory. This, among other things, puts a `ldlinux.c32` file, size 116524 bytes, in that directory. This file does not match `modules/6/ldlinux.c32`, size 122308 bytes, in the `syslinux_modules.zip` archive. The other modules do. The original `ldlinux.c32` in the iso image also matches `modules/6/ldlinux.c32`. This makes me suspect a version mismatch between the syslinux6 binary and the modules/6 collection.
- The 32-bit `syslinux6` binary does indeed write out the correct `ldlinux.c32`. The 64-bit `syslinux` produces the incompatible version of the same module. The 64-bit binary does not seem to come from the official distribution, either; the `ldlinux.c32` binary it incorporates has probably been compiled with debugging disabled.
- When I use my distribution’s packaged syslinux 6.03 amd64 and replace all modules in the target directory with those from my distribution’s package, the CloneZilla boot menu appears as expected.

Possible solutions:
- Avoid bundling 64-bit binaries and add libc6:i386 as a dependency, OR
- Bundle syslinux binaries and modules that you build yourself, so you can guarantee they are compatible.

User-side workaround:
- After starting `multibootusb`, extract the files in `syslinux_linux.zip` archive over those in `~/.multibootusb/syslinux/bin`. This needs to be repeated after each start, because `multibootusb` always overwrites them on start.

**Comment by mbusb** [comment]
Thank you very much for pointing to the right direction. Fix included in the latest release...

**Comment by JohnRobson** [comment]
I installed "gparted-live-0.28.1-1-i686.iso" (http://gparted.org/download.php)

Failed to load libcom32.c32
Failed to load COM32 file vesamenu.c32

I also extract "/usr/share/multibootusb/data/tools/syslinux/syslinux_linux.zip" to 'multibootusb/syslinux', but didn't work.
