### ISSUE TITLE
Install syslinux option has missing files

### ISSUE THREAD

**Issue by omer-musa-battal** [mbusb/multibootusb#493]
I have installed python3-multibootusb_9.2.0-1_all.deb on ubuntu 18.04. When I install syslinux using the gui, the program does not copy the following files in <usb_name>/multibootusb/ :

- multibootusb/mboot.c32
- multibootusb/plpbt
- multibootusb/syslinux.bin

and this causes some file not found errors at runtime. I wonder if this is an issue specific to the deb package, or is this the case when the application is built from source as well.

**Comment by phweyland** [comment]
On Debian 10, Install on "Install Syslinux" tab makes MutltibootUSB - 9.2.0 end without message.

**Comment by omer-musa-battal** [comment]
Well, I have been using [Ventoy](https://github.com/ventoy/Ventoy) these days, which seems like a better software for now.
I do not think there is any point in keeping this issue open, so I am closing it.
