### ISSUE TITLE
Ubuntu 16.04 ISO: Syslinux install failure, remounted as read only

### ISSUE THREAD

**Issue by awisus** [mbusb/multibootusb#54]
eddy-geek's hack (see gotnosocks@a675d81) may be working on Windows, but not on Linux.

Made a similar change on Ubuntu 16.04 (should be working on other OSs as well):

open /usr/lib/python2.7/dist-packages/scripts/update_cfg.py for editing
add on line 16: from subprocess import call
add on line 204: call(["mount", "-o", "remount,rw", config.usb_disk])
After having done so, MultibootUSB will be installing the Ubuntu ISO correctly.

**Comment by awisus** [comment]
Pull requested the change: https://github.com/mbusb/multibootusb/pull/55/commits/30bb711193905b0aaab7415ef5615460f75ca2fa

**Comment by mbusb** [comment]
Thanks for the pull request. Can you explain how does your code solves the problem (which was already solved earlier by eddy-geek) The disk is already remounted using ` admin.adminCmd(["mount", "-o", "remount,rw", config.usb_disk])` and again you are using `call(["mount", "-o", "remount,rw", config.usb_disk])` to remount again.

**Comment by awisus** [comment]
Greets and thanks for your quick response,

on my machine (Ubuntu 16.04), having installed multibootusb normally and having applied the fix by eddy-geek, the terminal outputs that adminCmd is an unknown attribute of admin (Python AttributeError). So I had to do another fix, replacing `admin.adminCmd(["mount", "-o", "remount,rw", config.usb_disk])`, which exactly does the same as eddy-geek's one is supposed to: remounting the working USB drive with write permissions (multibootusb makes is read-only when installing syslinux with the Ubuntu ISO). 

I don't know which environment eddy-geek was using so that his fix worked for him and others alike. Perhaps my suggestions works on a larger base?

**Comment by mbusb** [comment]
I think you have installed the release version of multibootusb and the the fix was done for the development version. Download the master branch/ development files and try.

**Comment by awisus** [comment]
Thank you very much for the advise!
My installation really was missing the adminCmd method in scripts/admin.

So let's see it like that: Now we have another solution saving some code :D

So let's just close this issue :)
