### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by RafaelLinux** [mbusb/multibootusb#549]
I like really multibootusb, despite is not in my distro repository. However, is outdated at least 4 years ago. I can see that even in bugs/features request no one reply to users ....

Is this project dead?

**Comment by robotshateme** [comment]
Dead. No actions in 2 years. I advise using ventoy as its easier to use (just install on a usb and copy isos onto it) and actively developed,

**Comment by RafaelLinux** [comment]
Yes, I know and use Ventoy. But multibootUSB is really good precisely to TEST and BOOT Ventoy made USB sticks. MultibootUSB ability to boot from ISOs and USBs using QEMU is really fantastic.
If project is dead, maybe Ventoy developers. could add that feature to their application.

Thank you for your clarification.
