### ISSUE TITLE
Limit persistent size to 3Gb on fat filesystem

### ISSUE THREAD

**Issue by lu6fer** [mbusb/multibootusb#58]
If you choose 4Gb persitent size on a FAT filesystem you get an error, but multibootusb does'nt prompt you.
Limit persitent size to 3Gb if filesystem is FAT will to the tricks

**Comment by mbusb** [comment]
Fixed in the latest development version. Will push the code soon.

**Comment by mbusb** [comment]
User can choose the size from GUI now. No persistence data shipped with multibootusb 8.0.0 release...
