### ISSUE TITLE
can't add ubuntu-14.04-server-amd64.iso

### ISSUE THREAD

**Issue by rdhia** [mbusb/multibootusb#6]
OS: ubuntu 12.04.4
python --version
Python 2.7.3

ubuntu:~$ /usr/bin/multibootusb 
Syslinux exist in multibootusb directory.
['pics', 'boot', 'EFI', 'isolinux', 'dists', 'pool', '.disk', 'install', 'preseed', 'doc']
iso extract directory is not empty.
Removing junk files...
.../.multibootusb/iso_cfg_ext_dir/pics
.../.multibootusb/iso_cfg_ext_dir/boot
.../.multibootusb/iso_cfg_ext_dir/EFI
.../.multibootusb/iso_cfg_ext_dir/isolinux
.../.multibootusb/iso_cfg_ext_dir/dists
.../.multibootusb/iso_cfg_ext_dir/pool
.../.multibootusb/iso_cfg_ext_dir/.disk
.../.multibootusb/iso_cfg_ext_dir/install
.../.multibootusb/iso_cfg_ext_dir/preseed
.../.multibootusb/iso_cfg_ext_dir/doc
/usr/bin/sudo
RRIP: rrip_offset 0
.../ubuntu-14.04-server-amd64.iso
Testing integrity of ubuntu-14.04-server-amd64.iso
Integrity passed...
os.path.dirname=/isolinux
[]
Traceback (most recent call last):
  File "/usr/bin/multibootusb", line 292, in onCreateClick
    self.create_mbusb()
  File "/usr/bin/multibootusb", line 493, in create_mbusb
    if re.search(r'sources', var.iso_file_list, re.I):
  File "/usr/lib/python2.7/re.py", line 142, in search
    return _compile(pattern, flags).search(string)
TypeError: expected string or buffer

**Comment by stamatovg** [comment]
This fix maybe is only in Ubuntu because i have problem in Ubuntu 14.04 to add *buntu OS
