### ISSUE TITLE
Unable to boot gparted

### ISSUE THREAD

**Issue by shayne** [mbusb/multibootusb#61]
Took me a while to get things working. I'm running of latest master.

For others: make sure you have a DOS partition table. I created a single partition, formatted to ext3. (also tried vfat).

The issue:

Installation of gparted reports successful, but i receive the following error when running in Qemu. I can confirm at least two other ISOs work.

![deepinscreenshot20161005230014](https://cloud.githubusercontent.com/assets/79330/19142064/8d93e04a-8b4f-11e6-9231-46e3dc03b3a4.png)

**Comment by shayne** [comment]
Looks to be related to #49

**Comment by mbusb** [comment]
Latest release 8.0.0 should fix this.
