### ISSUE TITLE
don't start

### ISSUE THREAD

**Issue by PowaBanga** [mbusb/multibootusb#64]
hi, I am on ubuntu 15.10, and the program don't start : 

```
sudo multibootusb-pkexec 
Starting multibootusb GUI...
Traceback (most recent call last):
  File "/usr/bin/multibootusb", line 98, in <module>
    start_gui()
  File "/usr/bin/multibootusb", line 47, in start_gui
    from scripts import mbusb_gui
  File "/usr/lib/python3/dist-packages/scripts/mbusb_gui.py", line 13, in <module>
    from PyQt5 import QtCore, QtGui, QtWidgets
ImportError: No module named 'PyQt5'
```

**Comment by mbusb** [comment]
There is a bug in the Debian package which does not pull in all dependencies. I discovered this just few hours ago when I was testing under Debian. You can issue the following command to solve the issue temporarily:-

`sudo apt-get install python3-pyqt5 parted mtools python3-dbus`

Then you will be able to start the gui. On a side note, no need to issue sudo if you are using multibootusb-pkexec command.

**Comment by PowaBanga** [comment]
good work !
I support really this project, because multisystem don't have any rpm packages, I must find my usb stick ^^ haha
