### ISSUE TITLE
v8.0.0 fails to launch on Windows 7

### ISSUE THREAD

**Issue by go2null** [mbusb/multibootusb#65]
When double-click on `multibootusb-8.0.0.exe` in Windows 7, I get the following error:
    
     multibootusb-8.0.0.exe - Entry Point Not Found
    -------------------------------------------------
    (X) The procedure entry point ecrtbase.terminate could not be located in
         the dynamic link library api-ms-win-crt-runtime-l1-1-0.dll.

When this is closed, the following error message appears:

    Fatal Error!
    ------------
    /!\  Error loading Python DLL: C:\Windows\TEMP\_MEI87362\python35.dll
         (error code 127)

Verified that the files exist.

NOTE: This occurs whether running as regular user or **Run as administrator**.

**Comment by mbusb** [comment]
I think this only affects single file executable (version 8.0.0). Can you try the latest version and report back. If same probelm still exist, then you must install this windows update package https://support.microsoft.com/en-gb/kb/2999226. Let me know if that helps.

**Comment by mbusb** [comment]
Solution is listed and hope that you have solved it. Closing the issue now. Feel free to open a new issue if have an issue.
