### ISSUE TITLE
iso is not supported at the moment

### ISSUE THREAD

**Issue by PowaBanga** [mbusb/multibootusb#70]
I try to install opensuse in my usb, but I have a popup who appear : 

> Sorry.
> openSUSE-Leap-42.1-DVD-x86_64.iso is not supported at the moment
> Please email this issue to feedback.multibootusb@gmail.com

![popup](http://i.imgur.com/rKLSKWk.png)

So I post here, I think that's it is the same, but in best.

**Comment by mbusb** [comment]
Tested the latest **openSUSE-Leap-42.**2**-DVD-x86_64.iso** and it works perfectly fine. You must ensure not to use FAT filesystem as it require an iso to be copied to the USB disk (in which FAT has a limitation of 4 GB).
