### ISSUE TITLE
Crash when browsing ISO on wayland

### ISSUE THREAD

**Issue by bagage** [mbusb/multibootusb#71]
## Issue

Using master version on Debian / gnome-shell / Wayland, application crashes when it tries to open the filebrowser:

> Starting multibootusb GUI...
Using pyudev for detecting USB drives...
Cleaning old multibootusb directory...
Extracting syslinux to multibootusb directory...
Host OS is 64 bit...
Extracting syslinux 64 bit...
Extracting syslinux modules to multibootusb directory...
(python3:26783): Gdk-WARNING **: /build/gtk+3.0-3.21.6/./gdk/x11/gdkwindow-x11.c:5554 drawable is not a native X11 window
(python3:26783): GLib-GObject-WARNING **: invalid cast from 'GdkWaylandDisplay' to 'GdkX11Display'
zsh: segmentation fault  python3 multibootusb

## Workaround (for now)

To make it work, I have to use X11 backend using `GDK_BACKEND=x11 multibootusb`.

**Comment by mbusb** [comment]
Please refer to the comment by me on this issue https://github.com/mbusb/multibootusb/issues/72. Let me know if that helps.

**Comment by bagage** [comment]
This does not help; however the issue is not specific to multibootusb since all QT apps I am using have the same issue.

**Comment by bagage** [comment]
You can see several apps having the issue [here](https://bugzilla.gnome.org/show_bug.cgi?id=769743), [there](https://bugreports.qt.io/browse/QTBUG-55583) or [here](https://bugs.launchpad.net/calibre/+bug/1600621). One work-around would be not to use the native filechooser, but I think waiting for the bug to be fixed is fine.
