### ISSUE TITLE
Qemu Boot USB not working

### ISSUE THREAD

**Issue by bagage** [mbusb/multibootusb#72]
When trying to simulate USB Boot via QEMU tab, it fails silently and I can see in logs:

> /usr/bin/qemu-system-x86_64
qemu-system-x86_64 exists...
Executing ==> qemu-system-x86_64 -hda /dev/sdc -m 1024 -vga std
qemu-system-x86_64: -hda /dev/sdc: Could not open '/dev/sdc': Permission denied

`/dev/sdc` is indeed the USB key, but I am running multibootusb as non-root user. It happens both when the USB key is empty and after I filled it with multiple ISO. I cannot test if it works with root user due to bug #71.

**Comment by mbusb** [comment]
> Permission denied

It is verry clear. How did you invoke multibootusb? You must use 

> multibootusb-pkexec

 from terminal.

**Comment by bagage** [comment]
Indeed, thanks. Though since everything else works as expected, it would be nice to have some disclaimer "You should be running this as root" and/or some error display on the GUI. 
Might you consider adding it?

**Comment by mbusb** [comment]
Thanks for the suggestion. I will do that in future release.

**Comment by mbusb** [comment]
Feature implemented in the development version.
