### ISSUE TITLE
Don't show exit confirmation popup

### ISSUE THREAD

**Issue by bagage** [mbusb/multibootusb#73]
Every-time you close the application, the pop-up "Do you really want to quit" appears. It is quite annoying and not used anymore in 2016; most applications would just quit, as expected by user.
If this pop-up is a security to avoid quitting in the middle of USB writing, it would be better in my opinion t display it only if there is pending work.
Moreover this pop-up also prevents the system from shutting down.

**Comment by mbusb** [comment]
Good point. Will consider in future release.

**Comment by mbusb** [comment]
Implemented in the development version.
