### ISSUE TITLE
$ multibootusb /usr/bin/env: ‘python\r’: No such file or directory

### ISSUE THREAD

**Issue by mikaere** [mbusb/multibootusb#75]
Hi, I have installed multibootusb from repo on Fedora25 and got python\r error (as in subject).

Fixed with sudo dos2unix /usr/local/bin/multibootusb

Work great now, thanks for this app.

Regards,
M.

**Comment by mbusb** [comment]
> Hi, I have installed multibootusb from repo on Fedora25

Which repo are you talking about?

Thanks for the fix.

**Comment by mikaere** [comment]
github repo

**Comment by mbusb** [comment]
My bad.

**Comment by mbusb** [comment]
Fixed in the latest commit.
