### ISSUE TITLE
"Creating persistence file" when I chose 0 MB of persistence.

### ISSUE THREAD

**Issue by Aqa-Ib** [mbusb/multibootusb#77]
Hello mister,

I am using multibootusb version 8.3.0 under Archlinux. 
When I add an iso image of some live systems such as clonezilla or rescatux, multibootusb starts "creating persistence file". It takes too long to finish the process, and when it finish, it has taken some GiB of space of my usb memory. Seeing that the iso image of clonezilla is 193 MiB, it can't take various GiB descompressed, so the problem is that "persistence file", that I don't know why it's created because I chose 0 B of persistence in multibootusb, and I don't see any option to disable it. 
On the other hand, when I chose an iso image of Archlinux, it does not create a persistence file. I don't know why it creates it for the iso images of clonezilla and rescatux when I chose 0 MB of persistence. That's why I am opening this report, and the problem is that it is taking some GiB of space from my usb memory.

This is the iso image of clonezilla that I am using: http://rwthaachen.dl.osdn.jp/clonezilla/66768/clonezilla-live-2.5.0-5-i686-pae.iso

Thanks a lot,
Regards.

**Comment by mbusb** [comment]
This bug has been fixed in the development version. You should see the new
version soon.

**Comment by Aqa-Ib** [comment]
Ok, I will wait for it.
Thank you very much for this great program.

**Comment by mbusb** [comment]
New version is released with this bug fix.
