### ISSUE TITLE
MultiBootUSB FAT USB stick not recognised on a UEFI system 

### ISSUE THREAD

**Issue by sueridgepipe** [mbusb/multibootusb#81]
Apologies if this is a silly question, still wrapping my head around this stuff.

I have setup multiple live environments on a fat32 USB drive and they are not recognised on my machine, which uses UEFI, it just continues through to GRUB menu.  BIOS settings has USB first in boot priority order.

Does MBUSB work on UEFI systems?  

Do I have to reformat my FAT32 USB stick with a GPT partition and re-install my live environments using MSUSB in order for it to be UEFI bootable?

Edit

I have another FAT32 USB stick with a single Linux environment on it and my system recognises it as bootable and successfully boots into it.  

I manually deleted everything off my MSUSB stick, then used MultiBootUSB to re-install only the Live Linux ISO that worked above.  My system is not recognising this MSUSB stick as bootable, it continues through to GRUB.

**Comment by mbusb** [comment]
No uefi support as of now.

**Comment by sueridgepipe** [comment]
Bummer, are you planning on supporting UEFI boot in later releases?

All my systems are UEFI boot, so I guess I'll have to temporarily enable Legacy BIOS boot mode if I want to boot of a MultiBootUSB stick then.

**Comment by mbusb** [comment]
Plan is there but I can't give any time frame for the implementation.

**Comment by Kendos-Kenlen** [comment]
I'm looking for this feature too. UEFI is now used in many computers and changing to legacy mode or hybrid mode force me to enter the security keys of my Windows, so not really confortable.

I hope you'll support UEFI systems soon.

**Comment by el-Salmon** [comment]
If you need UEFI mode, take a look [aguslr multiboot](https://github.com/aguslr/multibootusb)

**Comment by slipttees** [comment]
wait UEFI support..

**Comment by TheZoker** [comment]
+1

**Comment by arthurflor** [comment]
+1

**Comment by TjWallas** [comment]
Bump.

I am also in favor of having UEFI support in the near future. There has been a lot of action within the security community regarding topics like: Secure boot, verifiable BIOS, ...etc) recently.
https://hardenedlinux.github.io/system-security/2017/03/17/debian_hardened_boot.html

**Comment by jphein** [comment]
I believe grub2 provides UEFI support. There is already a ticket here requesting grub support:  https://github.com/mbusb/multibootusb/issues/102

**Comment by mbusb** [comment]
Please download the source from devel branch and provide feedback. Initial UEFI boot support has been implemented.

**Comment by alindt** [comment]
Give the [latest release](https://github.com/mbusb/multibootusb/releases) (8.6.0) a try

**Comment by mbusb** [comment]
Implemented since version 8.6.0. Closing the issue.
