### ISSUE TITLE
Cannot test ISO installer

### ISSUE THREAD

**Issue by bagage** [mbusb/multibootusb#88]
Currently, in QEMU tab, Boot USB only allows you to boot MultiBootUSB keys I believe (eg one with a partition, cf #38). If one uses ISO Imager, it will yield:

```
Extracting syslinux modules to multibootusb directory...
/usr/bin/qemu-system-x86_64
qemu-system-x86_64 exists...
Executing ==> qemu-system-x86_64 -hda  -m 2047 -vga std
qemu-system-x86_64: -hda -m: Could not open '-m': No such file or directory
```

However, running `qemu-system-x86_64 -hda /dev/sdc -m 2047 -vga std` **does** work as well, do you think it would be doable to add support of it?

**Comment by mbusb** [comment]
No. This should work. I have tested it again and it works as expected.

**Comment by alindt** [comment]
@bagage, could you try the latest master and/or devel branches and see if the problem persists?

**Comment by mbusb** [comment]
Tested again under Linux and Windows. Both working fine. Closing the issue.
