### ISSUE TITLE
Fails to check for a bunch of dependency

### ISSUE THREAD

**Issue by bagage** [mbusb/multibootusb#89]
multibootusb assume many other packages are present while never complaining about them if they are missing. Thanks to the logs:

* `mcopy` was missing, so multibootusb could not create the syslinux file for the USB key, making it unbootable. On debian, I add to install `mtools`
* `7z` was missing, so multibootusb could not decompress ISO file and crashed. On debian, I add to install `p7zip-full`.
* `pyudev` was missing, so multibootusb could not detect any USB key. On debian, I add to install `python3-pyudev`.

By the way I'd love to be able to install multibootusb via `pip` or debian packages - is there anything of this side?

**Comment by mbusb** [comment]
Here is the complete information about the multibootusb debian package:-

```
$ dpkg -I ../../multibootusb/release/8.4.0/Linux/python3-multibootusb_8.4.0-1_all.deb 
 new debian package, version 2.0.
 size 4190312 bytes: control archive=3247 bytes.
     521 bytes,    11 lines      control              
    6530 bytes,    74 lines      md5sums              
     170 bytes,     9 lines   *  postinst             #!/bin/sh
     413 bytes,    12 lines   *  prerm                #!/bin/sh
 Package: python3-multibootusb
 Source: multibootusb
 Version: 8.4.0-1
 Architecture: all
 Maintainer: Sundar <feedback.multibootusb@gmail.com>
 Installed-Size: 5364
 Depends: python3, python3:any (>= 3.3.2-2~), python3-pyqt5, parted, util-linux, mtools, python3-dbus, p7zip-full, python3-six
 Section: system
 Priority: optional
 Description: Create multi boot live Linux on a USB disk...
  multibootusb is an advanced cross-platform application for installing/uninstalling Linux operating systems on to a single USB flash drives.
```
So the dependencies you have listed are already present in the package. `pyudev` was not included as part of dependency as the package itself in shipped as part of the software. 

I could not find a package called `mcopy` in debian repo. Can you please explain more about this?

> install multibootusb via pip or debian packages 

No. At least not as of now. But I would be happy if someone can maintain this on this front.

**Comment by alindt** [comment]
As far as I can see from the sources, the dependencies issue is addressed on Linux distros at package building time:

**.deb**
```
Depends3: python3-pyqt5, parted, util-linux, mtools, python3-dbus, python3-pyudev, p7zip-full, python3-six
```

**.rpm**
``` 
Requires = python3-qt5, parted, util-linux, mtools, python3-dbus, python3-pyudev, p7zip, p7zip-plugins, python3-six
```

**Comment by mbusb** [comment]
It woks on on debian. As this post is relevant to debaian and issue is resolved, I am closing the issue.
