### ISSUE TITLE
Lakka + Librelec Support?

### ISSUE THREAD

**Issue by diskotechjam** [mbusb/multibootusb#91]
Hi, I posted a submitted this question on the main site, but I'll post it here also in case anyone else has an recommendations. I am looking to create a dual boot usb using LibreElec (https://libreelec.tv/ ) and Lakka ( http://www.lakka.tv/ ) but both of these distribution only provide img.gz files for installation. Can multibootusb use these types of images rather than ISOs?

**Comment by mbusb** [comment]
Latest push in devel branch has a support for your distro using memdisk. Also you can still write *.img using `Write ISO to USB`, though the method is destructive.
