### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Wabuo** [mbusb/multibootusb#92]
``` sh
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/scripts/mbusb_gui.py", line 183, in browse_iso
    per_availability = persistence.persistence_distro(config.distro, config.usb_disk, config.iso_link)[0]
  File "/usr/lib/python3.6/site-packages/scripts/persistence.py", line 34, in persistence_distro
    if usb_free_size > fat_max_size:
TypeError: '>' not supported between instances of 'str' and 'int'
```

**Comment by Wabuo** [comment]
@bagage Can you also fix this?

**Comment by froalker** [comment]
You have to mount your usb first. That will solve the Problem.
In file scripts/usb.py line 237 returns a String "No_Mount" as usb_free_size and this is compared with the fat_max_size in file scripts/persistence.py line 34.
There should be an automatic mount function.

**Comment by Wabuo** [comment]
Or at least an error message and an option to retry. A Silent crash is really bad ...

PS: Thx for your answer and thank you to everybody who made this great piece of software.

**Comment by mbusb** [comment]
Now multibootusb will automatically mount drives if they are not mounted. This will be released as part of next version. This should fix the issue.
