### ISSUE TITLE
Kaspersky Anti Virus LiveCD doesnt work

### ISSUE THREAD

**Issue by cborne** [mbusb/multibootusb#96]
Hello, no problem for install, no error but the iso doesnt appear in the list. 

https://support.kaspersky.com/fr/viruses/rescuedisk

**Comment by mbusb** [comment]
It works for me without an issue. Please provide the log file.

**Comment by cborne** [comment]
hi, where can i found the log ?

**Comment by cborne** [comment]
here : 

08:35:02,67 root INFO Starting multibootusb GUI...
08:35:02,411 root INFO Using pyudev for detecting USB drives...
08:35:02,418 root INFO No USB device found...
08:35:02,424 root INFO Cleaning old multibootusb directory...
08:35:02,436 root INFO Extracting syslinux to multibootusb directory...
08:35:02,437 root INFO Host OS is 64 bit...
08:35:02,437 root INFO Extracting syslinux 64 bit...
08:35:02,452 root INFO Extracting syslinux modules to multibootusb directory...
08:38:17,16 root INFO Starting multibootusb GUI...
08:38:17,230 root INFO Using pyudev for detecting USB drives...
08:38:17,341 root INFO Cleaning old multibootusb directory...
08:38:17,349 root INFO Extracting syslinux to multibootusb directory...
08:38:17,349 root INFO Host OS is 64 bit...
08:38:17,350 root INFO Extracting syslinux 64 bit...
08:38:17,362 root INFO Extracting syslinux modules to multibootusb directory...
08:38:37,303 root INFO  This disc don't support RRIP
08:38:37,477 root INFO Persistence is not available for kav_rescue_10.iso
08:38:44,122 root INFO USB Disk is /dev/sdc1
08:38:44,122 root INFO USB Label is No_Label
08:38:44,122 root INFO USB UUID is 318E-7EB0
08:38:44,122 root INFO USB Mount path is /media/cyrille/318E-7EB0
08:38:44,122 root INFO Total size of the disk is 14.9G
08:38:44,122 root INFO Total used size  is 8.6G
08:38:44,122 root INFO Total size left on the disk is 6.3G
08:38:44,122 root INFO FileSystem is vfat
08:38:44,122 root INFO Vendor is SanDisk
08:38:44,123 root INFO Model is Cruzer_Blade
08:38:44,123 root INFO Name of the ISO file is kav_rescue_10.iso
08:38:44,123 root INFO Distro type detected is kaspersky
08:38:44,159 root INFO multibootus directory already exist. Not copying.
08:38:44,159 root INFO Persistence choosen is 0 MB
08:38:51,154 root INFO Installing kav_rescue_10.iso on /media/cyrille/318E-7EB0/multibootusb/kav_rescue_10
08:40:12,539 root INFO ISO extracted successfully. Sync is in progress...
08:40:14,639 root INFO Distro extraction completed...
08:40:14,830 root INFO Distro does not use isolinux for booting ISO.
08:40:14,880 root INFO 
Executing ==> /root/.multibootusb/syslinux/bin/syslinux4 -i -d multibootusb /dev/sdc1

08:40:14,973 root INFO 
Default syslinux install is success...

08:40:14,979 root INFO 
mbr install is success...

08:40:15,37 root INFO 
Disk /dev/sdc already has boot flag.

08:40:15,150 root INFO Updating distro specific config files...

**Comment by cborne** [comment]
If you look at syslinux.cfg there is no kav

#start boot-repair-disk-32bit
LABEL boot-repair-disk-32bit
MENU LABEL boot-repair-disk-32bit
BOOT /multibootusb/boot-repair-disk-32bit/isolinux/ubuntu.bs
#end boot-repair-disk-32bit
#start boot-repair-disk-64bit
LABEL boot-repair-disk-64bit
MENU LABEL boot-repair-disk-64bit
BOOT /multibootusb/boot-repair-disk-64bit/isolinux/ubuntu.bs
#end boot-repair-disk-64bit
#start clonezilla-live-20161121-yakkety-amd64
LABEL clonezilla-live-20161121-yakkety-amd64
MENU LABEL clonezilla-live-20161121-yakkety-amd64
BOOT /multibootusb/clonezilla-live-20161121-yakkety-amd64/syslinux/debian.bs
#end clonezilla-live-20161121-yakkety-amd64
#start debian-8.7.1-i386-xfce-CD-1
LABEL debian-8.7.1-i386-xfce-CD-1
MENU LABEL debian-8.7.1-i386-xfce-CD-1
BOOT /multibootusb/debian-8.7.1-i386-xfce-CD-1/isolinux/debian-install.bs
#end debian-8.7.1-i386-xfce-CD-1
#start ophcrack-vista-livecd-3.6.0
LABEL ophcrack-vista-livecd-3.6.0
MENU LABEL ophcrack-vista-livecd-3.6.0
BOOT /multibootusb/ophcrack-vista-livecd-3.6.0/boot/isolinux/slitaz.bs
#end ophcrack-vista-livecd-3.6.0
#start redobackup-livecd-1.0.4
LABEL redobackup-livecd-1.0.4
MENU LABEL redobackup-livecd-1.0.4
BOOT /multibootusb/redobackup-livecd-1.0.4/isolinux/ubuntu.bs
#end redobackup-livecd-1.0.4
#start debian-8.7.1-i386-lxde-CD-1
LABEL debian-8.7.1-i386-lxde-CD-1
MENU LABEL debian-8.7.1-i386-lxde-CD-1
BOOT /multibootusb/debian-8.7.1-i386-lxde-CD-1/isolinux/debian-install.bs
#end debian-8.7.1-i386-lxde-CD-1
#start debian-8.7.1-amd64-xfce-CD-1
LABEL debian-8.7.1-amd64-xfce-CD-1
MENU LABEL debian-8.7.1-amd64-xfce-CD-1
BOOT /multibootusb/debian-8.7.1-amd64-xfce-CD-1/isolinux/debian-install.bs
#end debian-8.7.1-amd64-xfce-CD-1
#start rescatux-0.40b11
LABEL rescatux-0.40b11
MENU LABEL rescatux-0.40b11
BOOT /multibootusb/rescatux-0.40b11/isolinux/debian.bs
#end rescatux-0.40b11

**Comment by evansgp** [comment]
I think I might have had the same issue. Here is what I had in my console:

```
Installing kav_rescue_10.iso on /media/root/Ubuntu 16.04.2 LTS amd64/multibootusb/kav_rescue_10
ISO extracted successfully. Sync is in progress...############################|
Distro extraction completed...
Distro does not use isolinux for booting ISO.

Executing ==> /home/gareth/.multibootusb/syslinux/bin/syslinux4 -i -d multibootusb /dev/sdb1


Default syslinux install is success...

1+0 records in
1+0 records out
440 bytes copied, 0.000597929 s, 736 kB/s

mbr install is success...


Checking boot flag on /dev/sdb

Executing ==>  parted /dev/sdb set 1 boot on
Information: You may need to update /etc/fstab.

                                                                          
Boot flag set to bootable /dev/sdb
Updating distro specific config files...
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/scripts/mbusb_gui.py", line 212, in install_syslinux
    update_distro_cfg_files(config.iso_link, config.usb_disk, config.distro, config.persistence)
  File "/usr/lib/python3/dist-packages/scripts/update_cfg_file.py", line 88, in update_distro_cfg_files
    os.path.join(usb_mount, 'multibootusb', iso_basename(iso_link), 'kaspersky.cfg'))
  File "/usr/lib/python3.5/shutil.py", line 114, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/share/multibootusb/data/multibootusb/syslinux.cfg'
```

The GUI appeared as if it stopped half way through the operation as the ISO did not appear in the list but it also didn't give an error.

I found that on my system the file was located at /usr/share/multibootusb/data/tools/multibootusb/syslinux.cfg (note the extra 'tools' dir). I had installed multibootusb from python3-multibootusb_8.5.0-1_all.deb on the website.

I modified https://github.com/mbusb/multibootusb/blob/master/scripts/update_cfg_file.py#L87 to include the extra directory and everything worked.

I wasn't sure whether update_cfg_file.py was incorrect or the installer, sorry.

**Comment by alindt** [comment]
@cborne and @evansgp, could you try the latest master and/or devel branches and see if the problem persists?

**Comment by reddwarf4ever** [comment]
I added Kaspersky AV and it shows in the list, but the line just flickers and the app doesn't run

**Comment by alindt** [comment]
Give the [latest release](https://github.com/mbusb/multibootusb/releases) (8.6.0) a try

**Comment by reddwarf4ever** [comment]
Thanks

Will do, has the test USB / ISO's been improved ?

Can't seem to get either to work, great idea to test USB Distro's without continually rebooting the PC....

Thanks

**Comment by alindt** [comment]
MultibootUSB has no power over the ISO format, whether you boot the ISO directly or you write it to USB and then boot USB.

"Bootability" from other media than CD/DVD is an ISO property which is not present in some ISOs - only **hybrid** ISOs will boot from USB directly. You can check this property in MultibootUSB when opening an ISO by looking at the `Boot` field in the GUI - if it says `No`, then it's most probably not a hybrid ISO.

On Linux you can use `isohybrid` to make a hybrid ISO:

```
NAME
isohybrid — Post-process an ISO 9660 image for booting as a hard disk.

SYNOPSIS
isohybrid [OPTIONS] <boot.iso>

DESCRIPTION
The  isohybrid  utility  modifies  an ISO 9660 image generated with mkisofs, genisoimage, or compatible utilities, to be bootable as a CD-ROM or as a hard disk.
```

**Comment by reddwarf4ever** [comment]
Thanks
Does your program also have the capability to make a boot DVD, if not maybe this could be added, especially if comparability is higher....

Thanks

**Comment by reddwarf4ever** [comment]
All the ISO say False, which I assume means "No"
But most installing ok

In the tab write image to disk, it says write image to USB , it should say write image to USB or pen NOT disk, gets confusing with DVD CD burning.....called disk....

Wish you had an option to create an ISO to burn multiboot to a DVD

Thanks

**Comment by mbusb** [comment]
The distro works well. Tested on latest release. Closing the issue.
